/*
 * exercises-data.js - donnees statiques extraites de app.js (Vague 3.1, 2026-07-06).
 * Charge AVANT app.js (portee globale partagee). Aucune logique ici.
 */
const exercises = [
  {name:'Goblet squat kettlebell',kind:'Kettlebell',family:'general',sheet:1,art:'p0',sets:3,reps:8,cue:'Kettlebell contre le buste, pieds stables.',explain:'Descends entre les hanches, puis pousse le sol pour remonter.',goal:'Cuisses, fessiers et posture.',avoid:'Genoux qui rentrent ou dos arrondi.'},
  {name:'Pompes inclinées',kind:'Poids du corps',family:'general',sheet:1,art:'p1',sets:3,reps:8,cue:'Mains sur un plan de travail stable, une rambarde ou un rebord (plus c’est haut, plus c’est facile).',explain:'Corps en planche, amène la poitrine vers le support puis pousse. Baisse le support au fil des semaines pour progresser vers les pompes au sol.',goal:'Pectoraux, épaules et triceps — variante réglable sans matériel.',avoid:'Bassin qui tombe ou coudes très écartés.'},
  {name:'Fentes arrière',kind:'Poids du corps',family:'trail',sheet:1,art:'p2',sets:3,reps:8,cue:'Grand pas arrière, buste haut.',explain:'Descends en contrôle puis pousse dans le pied avant pour revenir debout.',goal:'Force unilatérale et stabilité pour le trail.',avoid:'Genou avant qui part vers l’intérieur.'},
  {name:'Soulevé de terre kettlebell',kind:'Kettlebell',family:'trail',sheet:1,art:'p3',sets:3,reps:10,cue:'Hanches en arrière, dos long.',explain:'La kettlebell descend près des jambes ; remonte en serrant les fessiers.',goal:'Chaîne postérieure et résistance en montée.',avoid:'Transformer le mouvement en squat ou arrondir le dos.'},
  {name:'Step-up escalier',kind:'Gilet lesté',family:'trail',sheet:1,art:'p4',sets:3,reps:10,cue:'Pied entier sur une marche d’escalier stable (gilet lesté en option).',explain:'Monte en poussant dans la jambe posée, contrôle totalement la descente. Une marche d’escalier ou un muret bas suffit.',goal:'Montées, quadriceps et équilibre — spécifique trail.',avoid:'Impulsion excessive avec la jambe au sol.'},
  {name:'Gainage planche',kind:'Poids du corps',family:'core',sheet:1,art:'p5',sets:3,reps:30,unit:'sec',cue:'Coudes sous épaules, bassin neutre.',explain:'Garde une ligne tête-hanches-talons et respire calmement.',goal:'Tronc solide pour porter et courir.',avoid:'Creuser le bas du dos ou retenir le souffle.'},
  {name:'Pompes classiques',kind:'Poids du corps',family:'general',sheet:2,art:'p0',sets:3,reps:8,cue:'Corps gainé, poitrine vers le sol.',explain:'Descends avec contrôle jusqu’à une amplitude confortable puis pousse fort.',goal:'Poussée du haut du corps.',avoid:'Nuque projetée ou bassin qui s’affaisse.'},
  {name:'Pompes diamants',kind:'Poids du corps',family:'general',sheet:2,art:'p1',sets:3,reps:6,cue:'Mains rapprochées sous la poitrine.',explain:'Garde les coudes proches du corps et réduis l’amplitude si nécessaire.',goal:'Triceps et contrôle de poussée.',avoid:'Forcer une amplitude douloureuse aux poignets.'},
  {name:'Pompes gilet lesté',kind:'Gilet lesté',family:'general',sheet:2,art:'p2',sets:3,reps:6,cue:'Charge légère, forme stricte.',explain:'Utilise le même trajet que les pompes classiques ; le gilet ne remplace pas la technique.',goal:'Poussée plus forte.',avoid:'Ajouter de la charge avant de maîtriser 10 pompes propres.'},
  {name:'Gainage latéral',kind:'Poids du corps',family:'core',sheet:2,art:'p3',sets:3,reps:25,unit:'sec',cue:'Épaule au-dessus du coude.',explain:'Soulève les hanches et maintiens une ligne longue sur le côté.',goal:'Obliques et stabilité du bassin.',avoid:'Épaule qui remonte vers l’oreille.'},
  {name:'Kettlebell swing',kind:'Kettlebell',family:'trail',sheet:2,art:'p4',sets:3,reps:12,cue:'Charnière de hanches, bras détendus.',explain:'Projette la kettlebell avec les hanches puis laisse-la revenir sous contrôle.',goal:'Puissance de hanches et endurance postérieure.',avoid:'Soulever avec les épaules ou arrondir le dos.'},
  {name:'Élévations mollets',kind:'Trail',family:'trail',sheet:2,art:'p5',sets:3,reps:15,cue:'Pieds parallèles, pause en haut.',explain:'Monte sur la pointe, marque une seconde puis redescends lentement.',goal:'Mollets et tolérance aux montées/descentes.',avoid:'Rebondir ou écourter la descente.'},
  {name:'Mountain climbers',kind:'Poids du corps',family:'conditioning',sheet:3,art:'p0',sets:3,reps:20,cue:'Épaules au-dessus des mains.',explain:'Depuis la planche, ramène alternativement les genoux sans perdre la ligne du dos.',goal:'Cardio, gainage et coordination.',avoid:'Rebondir sur les épaules ou cambrer.'},
  {name:'Hollow hold',kind:'Poids du corps',family:'core',sheet:3,art:'p1',sets:3,reps:20,unit:'sec',cue:'Bas du dos en contact avec le sol.',explain:'Allonge bras et jambes seulement tant que le dos reste plaqué.',goal:'Gainage antérieur.',avoid:'Allonger les jambes au prix d’un dos qui se creuse.'},
  {name:'Bear crawl',kind:'Poids du corps',family:'conditioning',sheet:3,art:'p2',sets:3,reps:20,unit:'pas',cue:'Genoux proches du sol, pas courts.',explain:'Avance main et pied opposé en gardant le tronc aussi immobile que possible.',goal:'Épaules, tronc et coordination.',avoid:'Hanches qui se balancent fortement.'},
  {name:'Split squat bulgare',kind:'Poids du corps',family:'trail',sheet:3,art:'p3',sets:3,reps:8,cue:'Pied arrière posé, jambe avant stable.',explain:'Descends verticalement en gardant le poids surtout sur la jambe avant.',goal:'Force unilatérale et contrôle de descente.',avoid:'Pousser fort dans le pied arrière.'},
  {name:'Marche fermier kettlebell',kind:'Kettlebell',family:'general',sheet:3,art:'p4',sets:3,reps:30,unit:'pas',cue:'Buste haut, pas calmes.',explain:'Marche sans te pencher, les épaules loin des oreilles et le tronc gainé.',goal:'Prise, posture et gainage utile.',avoid:'Courir ou laisser les charges tirer les épaules.'},
  {name:'Dead bug',kind:'Poids du corps',family:'core',sheet:3,art:'p5',sets:3,reps:10,cue:'Expire avant d’allonger le membre opposé.',explain:'Allonge lentement bras et jambe opposés puis reviens sans bouger le bassin.',goal:'Contrôle du tronc et du bassin.',avoid:'Bas du dos qui se soulève.'},
  {name:'Step-down escalier',kind:'Trail',family:'trail',sheet:4,art:'p0',sets:3,reps:8,cue:'Debout sur une marche d’escalier, descente latérale lente sur une jambe.',explain:'Depuis une marche, effleure le talon au sol sur le côté puis remonte avec la jambe restée sur la marche. Contrôle = protection des genoux en descente.',goal:'Quadriceps et contrôle excentrique des descentes.',avoid:'Laisser le genou s’effondrer vers l’intérieur.'},
  {name:'Soulevé de terre une jambe kettlebell',kind:'Kettlebell',family:'trail',sheet:4,art:'p1',sets:3,reps:8,cue:'Hanches carrées, jambe libre tendue derrière.',explain:'Bascule depuis les hanches et remonte en gardant l’équilibre sur une jambe.',goal:'Ischios, fessiers et stabilité.',avoid:'Tourner le bassin ou chercher trop bas.'},
  {name:'Pont fessier',kind:'Poids du corps',family:'general',sheet:4,art:'p2',sets:3,reps:12,cue:'Pieds proches des fessiers.',explain:'Pousse dans les talons, serre les fessiers en haut puis redescends lentement.',goal:'Fessiers et chaîne postérieure.',avoid:'Hypercambrer en haut du mouvement.'},
  {name:'Relevés tibiaux au mur',kind:'Trail',family:'trail',sheet:4,art:'p3',sets:3,reps:15,cue:'Dos au mur, talons au sol.',explain:'Relève les orteils vers les tibias puis repose-les en contrôle.',goal:'Tibias et protection des descentes.',avoid:'Décoller les talons ou aller trop vite.'},
  {name:'Chaise au mur',kind:'Poids du corps',family:'trail',sheet:4,art:'p4',sets:3,reps:30,unit:'sec',cue:'Dos au mur, cuisses proches de l’horizontale.',explain:'Respire et répartis le poids sur tout le pied.',goal:'Endurance des quadriceps.',avoid:'Douleur vive au genou ou position trop profonde.'},
  {name:'Squat cosaque',kind:'Poids du corps',family:'trail',sheet:4,art:'p5',sets:3,reps:6,cue:'Une hanche descend, autre jambe longue.',explain:'Déplace le poids latéralement avec un pied ancré et un buste fier.',goal:'Mobilité latérale et adducteurs.',avoid:'Forcer la profondeur si la hanche tire.'},
  {name:'Pike push-up',kind:'Poids du corps',family:'general',sheet:5,art:'p0',sets:3,reps:6,cue:'Hanches hautes, tête vers le sol.',explain:'Plie les bras pour amener le sommet du crâne près du sol puis repousse.',goal:'Épaules et triceps.',avoid:'Écraser la nuque ou perdre le contrôle des épaules.'},
  {name:'Rowing kettlebell un bras',kind:'Kettlebell',family:'general',sheet:5,art:'p1',sets:3,reps:10,cue:'Dos long, épaule loin de l’oreille.',explain:'Tire le coude vers la hanche, marque une pause puis redescends lentement.',goal:'Dos et stabilité de l’épaule.',avoid:'Tourner le buste ou tirer avec l’épaule vers le haut.'},
  {name:'Développé militaire kettlebell',kind:'Kettlebell',family:'general',sheet:5,art:'p2',sets:3,reps:8,cue:'Fessiers serrés, poignet neutre.',explain:'Presse la kettlebell au-dessus de la tête sans cambrer.',goal:'Épaules, triceps et gainage debout.',avoid:'Douleur à l’épaule ou dos qui se creuse.'},
  {name:'Floor press kettlebell',kind:'Kettlebell',family:'general',sheet:5,art:'p3',sets:3,reps:10,cue:'Coude touche légèrement le sol.',explain:'Allongé au sol, pousse la kettlebell vers le plafond puis redescends avec contrôle.',goal:'Pectoraux et triceps avec amplitude sécurisée.',avoid:'Verrouiller brutalement le coude.'},
  {name:'Bird dog',kind:'Poids du corps',family:'core',sheet:5,art:'p4',sets:3,reps:10,cue:'Main et genou opposés ancrés.',explain:'Allonge bras et jambe opposés sans faire tourner le bassin.',goal:'Stabilité lombaire et coordination.',avoid:'Chercher haut au prix d’un dos qui se creuse.'},
  {name:'Superman',kind:'Poids du corps',family:'core',sheet:5,art:'p5',sets:3,reps:12,cue:'Regard vers le sol, nuque longue.',explain:'Soulève légèrement bras et jambes, marque une pause puis relâche.',goal:'Endurance douce du dos.',avoid:'Forcer une grande extension lombaire.'},
  {name:'Tractions',kind:'Barre de traction',family:'general',sets:4,reps:5,cue:'Prise pronation largeur d’épaules, épaules engagées (basses).',explain:'Pars bras tendus, tire les coudes vers le bas jusqu’à passer le menton au-dessus de la barre, puis descends en contrôle complet jusqu’à l’extension.',goal:'Le tirage vertical roi : dos, biceps et poigne.',avoid:'Balancer (kipping), s’arrêter à mi-course ou lâcher la descente.'},
  {name:'Tractions supination',kind:'Barre de traction',family:'general',sets:3,reps:6,cue:'Paumes vers toi, largeur d’épaules, coudes près du corps.',explain:'Même trajet que la traction, mains en supination : davantage de biceps et souvent plus accessible pour progresser.',goal:'Force de tirage et biceps, marche vers la traction stricte.',avoid:'Coudes qui s’écartent ou amplitude écourtée.'},
  {name:'Tractions négatives',kind:'Barre de traction',family:'general',sets:4,reps:4,cue:'Menton au-dessus de la barre au départ (saut ou une marche pour monter).',explain:'Pars en haut et descends le plus lentement possible (3 à 5 s) jusqu’aux bras tendus. C’est LA brique pour construire ta première traction complète.',goal:'Construire la force de tirage quand la traction stricte n’est pas encore là.',avoid:'Se laisser tomber ou raccourcir la descente.'},
  {name:'Rowing australien',kind:'Barre de traction',family:'general',sets:3,reps:10,cue:'Barre réglée bas, corps gainé en planche inversée sous la barre.',explain:'Tire la poitrine vers la barre en serrant les omoplates, puis reviens bras tendus sous contrôle. Plus ton corps est horizontal, plus c’est dur.',goal:'Tirage horizontal : dos, posture et épaules saines pour équilibrer les pompes.',avoid:'Hanches qui tombent ou épaules qui montent vers les oreilles.'},
  {name:'Suspension barre',kind:'Barre de traction',family:'general',sets:3,reps:30,unit:'sec',cue:'Bras tendus, épaules actives (légèrement basses), respiration calme.',explain:'Reste suspendu en engageant les épaules sans plier les coudes. Renforce la poigne et décompresse la colonne.',goal:'Poigne, épaules et santé du haut du corps.',avoid:'Épaules totalement relâchées ou blocage de la respiration.'},
  {name:'Relevés de genoux suspendu',kind:'Barre de traction',family:'core',sets:3,reps:10,cue:'Suspendu bras tendus, épaules engagées.',explain:'Monte les genoux vers la poitrine en enroulant le bassin, puis redescends lentement sans balancer.',goal:'Tronc, fléchisseurs de hanche et anti-balancement — précieux en trail.',avoid:'Prendre de l’élan ou cambrer en redescendant.'},
  {name:'Pompes déficit',kind:'Poignées de pompes',family:'general',sets:3,reps:8,cue:'Mains sur les poignées, poitrine qui descend plus bas que les mains.',explain:'Profite des poignées pour descendre en grande amplitude, puis pousse fort. Poignets protégés par la prise neutre.',goal:'Poussée en amplitude complète : pectoraux, épaules et triceps.',avoid:'Descendre au-delà d’une gêne d’épaule ou casser la ligne du corps.'}
];
const programs = {
  fullbody: { name:'Hybride trail + force', desc:'3 séances force à alterner avec tes sorties course · barre, KB, poignées, gilet', days:['A · Tirage & poussée','B · Jambes & chaîne postérieure','C · Puissance & tronc'], workouts:[
    {title:'A · Tirage & poussée',duration:50,why:'Haut du corps équilibré tirage/poussée. À placer un jour sans grosse sortie course. Objectif : technique stricte et 2–3 répétitions en réserve, jamais l’échec.',exercises:[{name:'Tractions',sets:4,reps:5},{name:'Pompes gilet lesté',sets:3,reps:6},{name:'Rowing australien',sets:3,reps:10},{name:'Développé militaire kettlebell',sets:3,reps:8},{name:'Relevés de genoux suspendu',sets:3,reps:10}]},
    {title:'B · Jambes & chaîne postérieure',duration:50,why:'Jambes et chaîne postérieure : ça soutient directement ta foulée et protège genoux/ischios. À distance d’au moins 24 h d’une sortie intense.',exercises:[{name:'Goblet squat kettlebell',sets:3,reps:8},{name:'Soulevé de terre kettlebell',sets:3,reps:10},{name:'Split squat bulgare',sets:3,reps:8},{name:'Élévations mollets',sets:4,reps:15},{name:'Gainage planche',sets:3,reps:40}]},
    {title:'C · Puissance & tronc',duration:45,why:'Puissance de hanches et tronc anti-balancement pour le trail. Explosif au swing, gainé et contrôlé partout ailleurs.',exercises:[{name:'Kettlebell swing',sets:4,reps:12},{name:'Fentes arrière',sets:3,reps:10},{name:'Squat cosaque',sets:3,reps:6},{name:'Marche fermier kettlebell',sets:3,reps:30},{name:'Hollow hold',sets:3,reps:25}]}
  ]},
  ppl: { name:'Force & tractions (haut du corps)', desc:'3 séances orientées force du haut · barre de traction, poignées, KB', days:['Tirage vertical','Poussée','Équilibre & tronc'], workouts:[
    {title:'Tirage vertical',duration:45,why:'Construis des tractions solides. Si la traction stricte n’est pas encore là, la séance te fait progresser via négatives et rowing australien.',exercises:[{name:'Tractions',sets:4,reps:5},{name:'Tractions supination',sets:3,reps:6},{name:'Suspension barre',sets:3,reps:30},{name:'Relevés de genoux suspendu',sets:3,reps:10},{name:'Gainage latéral',sets:3,reps:25}]},
    {title:'Poussée',duration:45,why:'Poussée en amplitude complète. Les poignées protègent tes poignets et augmentent l’amplitude de travail.',exercises:[{name:'Pompes déficit',sets:3,reps:8},{name:'Pompes diamants',sets:3,reps:6},{name:'Développé militaire kettlebell',sets:3,reps:8},{name:'Floor press kettlebell',sets:3,reps:10},{name:'Marche fermier kettlebell',sets:3,reps:30}]},
    {title:'Équilibre & tronc',duration:40,why:'Rééquilibre tirage/poussée et renforce le tronc : la séance qui garde tes épaules saines sur la durée.',exercises:[{name:'Rowing australien',sets:3,reps:10},{name:'Pike push-up',sets:3,reps:6},{name:'Bird dog',sets:3,reps:10},{name:'Dead bug',sets:3,reps:10},{name:'Superman',sets:3,reps:12}]}
  ]},
  run: { name:'Spécial trail & course', desc:'Force courte à placer autour des sorties · jambes, mollets, tronc, poigne', days:['Force courte trail','Côtes & descentes','Tronc & poigne (léger)'], workouts:[
    {title:'Force courte trail',duration:40,why:'Peu d’exercices, bien faits, loin de la sortie longue. Unilatéral et chaîne postérieure pour une foulée solide.',exercises:[{name:'Soulevé de terre une jambe kettlebell',sets:3,reps:8},{name:'Split squat bulgare',sets:3,reps:8},{name:'Élévations mollets',sets:4,reps:15},{name:'Relevés tibiaux au mur',sets:3,reps:15},{name:'Gainage planche',sets:3,reps:40}]},
    {title:'Côtes & descentes',duration:35,why:'Prépare montées ET descentes (le vrai point faible de la plupart des coureurs) : beaucoup de contrôle excentrique.',exercises:[{name:'Fentes arrière',sets:3,reps:10},{name:'Step-down escalier',sets:3,reps:8},{name:'Squat cosaque',sets:3,reps:6},{name:'Chaise au mur',sets:3,reps:40},{name:'Élévations mollets',sets:4,reps:12}]},
    {title:'Tronc & poigne (léger)',duration:30,why:'Jour léger qui protège la régularité : gainage suspendu et poigne, sans entamer ta récupération pour la prochaine sortie.',exercises:[{name:'Relevés de genoux suspendu',sets:3,reps:10},{name:'Suspension barre',sets:3,reps:30},{name:'Dead bug',sets:3,reps:10},{name:'Bird dog',sets:3,reps:10},{name:'Hollow hold',sets:3,reps:20}]}
  ]}
};


if (typeof module !== "undefined" && module.exports) { module.exports = { exercises, programs }; }
