/*
 * exercises-data.js - donnees statiques extraites de app.js (Vague 3.1, 2026-07-06).
 * Charge AVANT app.js (portee globale partagee). Aucune logique ici.
 */
const exercises = [
  {name:'Goblet squat kettlebell',kind:'Kettlebell',family:'general',sheet:1,art:'p0',sets:3,reps:8,cue:'Kettlebell contre le buste, pieds stables.',explain:'Descends entre les hanches, puis pousse le sol pour remonter.',goal:'Cuisses, fessiers et posture.',avoid:'Genoux qui rentrent ou dos arrondi.'},
  {name:'Pompes inclinées',kind:'Poids du corps',family:'general',sheet:1,art:'p1',sets:3,reps:8,cue:'Mains sur un support solide, corps en planche.',explain:'Amène la poitrine vers le support puis pousse sans casser la ligne du corps.',goal:'Pectoraux, épaules et triceps.',avoid:'Bassin qui tombe ou coudes très écartés.'},
  {name:'Fentes arrière',kind:'Poids du corps',family:'trail',sheet:1,art:'p2',sets:3,reps:8,cue:'Grand pas arrière, buste haut.',explain:'Descends en contrôle puis pousse dans le pied avant pour revenir debout.',goal:'Force unilatérale et stabilité pour le trail.',avoid:'Genou avant qui part vers l’intérieur.'},
  {name:'Soulevé de terre kettlebell',kind:'Kettlebell',family:'trail',sheet:1,art:'p3',sets:3,reps:10,cue:'Hanches en arrière, dos long.',explain:'La kettlebell descend près des jambes ; remonte en serrant les fessiers.',goal:'Chaîne postérieure et résistance en montée.',avoid:'Transformer le mouvement en squat ou arrondir le dos.'},
  {name:'Step-up gilet',kind:'Gilet lesté',family:'trail',sheet:1,art:'p4',sets:3,reps:10,cue:'Pied entier sur une marche stable.',explain:'Monte en poussant dans la jambe posée, contrôle totalement la descente.',goal:'Montées, quadriceps et équilibre.',avoid:'Impulsion excessive avec la jambe au sol.'},
  {name:'Gainage planche',kind:'Poids du corps',family:'core',sheet:1,art:'p5',sets:3,reps:30,unit:'sec',cue:'Coudes sous épaules, bassin neutre.',explain:'Garde une ligne tête-hanches-talons et respire calmement.',goal:'Tronc solide pour porter et courir.',avoid:'Creuser le bas du dos ou retenir le souffle.'},
  {name:'Pompes classiques',kind:'Poids du corps',family:'general',sheet:2,art:'p0',sets:3,reps:8,cue:'Corps gainé, poitrine vers le sol.',explain:'Descends avec contrôle jusqu’à une amplitude confortable puis pousse fort.',goal:'Poussée du haut du corps.',avoid:'Nuque projetée ou bassin qui s’affaisse.'},
  {name:'Pompes diamants',kind:'Poids du corps',family:'general',sheet:2,art:'p1',sets:3,reps:6,cue:'Mains rapprochées sous la poitrine.',explain:'Garde les coudes proches du corps et réduis l’amplitude si nécessaire.',goal:'Triceps et contrôle de poussée.',avoid:'Forcer une amplitude douloureuse aux poignets.'},
  {name:'Pompes gilet lesté',kind:'Gilet lesté',family:'general',sheet:2,art:'p2',sets:3,reps:6,cue:'Charge légère, forme stricte.',explain:'Utilise le même trajet que les pompes classiques ; le gilet ne remplace pas la technique.',goal:'Poussée plus forte.',avoid:'Ajouter de la charge avant de maîtriser 10 pompes propres.'},
  {name:'Gainage latéral',kind:'Poids du corps',family:'core',sheet:2,art:'p3',sets:3,reps:25,unit:'sec',cue:'Épaule au-dessus du coude.',explain:'Soulève les hanches et maintiens une ligne longue sur le côté.',goal:'Obliques et stabilité du bassin.',avoid:'Épaule qui remonte vers l’oreille.'},
  {name:'Kettlebell swing',kind:'Kettlebell',family:'trail',sheet:2,art:'p4',sets:3,reps:12,cue:'Charnière de hanches, bras détendus.',explain:'Projette la kettlebell avec les hanches puis laisse-la revenir sous contrôle.',goal:'Puissance de hanches et endurance postérieure.',avoid:'Soulever avec les épaules ou arrondir le dos.'},
  {name:'Élévations mollets',kind:'Trail',family:'trail',sheet:2,art:'p5',sets:3,reps:15,cue:'Pieds parallèles, pause en haut.',explain:'Monte sur la pointe, marque une seconde puis redescends lentement.',goal:'Mollets et tolérance aux montées/descentes.',avoid:'Rebondir ou écourter la descente.'},
  {name:'Mountain climbers',kind:'Poids du corps',family:'conditioning',sheet:3,art:'p0',sets:3,reps:20,cue:'Épaules au-dessus des mains.',explain:'Depuis la planche, ramène alternativement les genoux sans perdre la ligne du dos.',goal:'Cardio, gainage et coordination.',avoid:'Rebondir sur les épaules ou cambrer.'},
  {name:'Hollow hold',kind:'Poids du corps',family:'core',sheet:3,art:'p1',sets:3,reps:20,unit:'sec',cue:'Bas du dos en contact avec le sol.',explain:'Allonge bras et jambes seulement tant que le dos reste plaqué.',goal:'Gainage antérieur.',avoid:'Allonger les jambes au prix d’un dos qui se creuse.'},
  {name:'Bear crawl',kind:'Poids du corps',family:'conditioning',sheet:3,art:'p2',sets:3,reps:20,unit:'pas',cue:'Genoux proches du sol, pas courts.',explain:'Avance main et pied opposé en gardant le tronc aussi immobile que possible.',goal:'Épaules, tronc et coordination.',avoid:'Hanches qui se balancent fortement.'},
  {name:'Split squat bulgare',kind:'Poids du corps',family:'trail',sheet:3,art:'p3',sets:3,reps:8,cue:'Pied arrière posé, jambe avant stable.',explain:'Descends verticalement en gardant le poids surtout sur la jambe avant.',goal:'Force unilatérale et contrôle de descente.',avoid:'Pousser fort dans le pied arrière.'},
  {name:'Marche fermier kettlebell',kind:'Kettlebell',family:'general',sheet:3,art:'p4',sets:3,reps:30,unit:'pas',cue:'Buste haut, pas calmes.',explain:'Marche sans te pencher, les épaules loin des oreilles et le tronc gainé.',goal:'Prise, posture et gainage utile.',avoid:'Courir ou laisser les charges tirer les épaules.'},
  {name:'Dead bug',kind:'Poids du corps',family:'core',sheet:3,art:'p5',sets:3,reps:10,cue:'Expire avant d’allonger le membre opposé.',explain:'Allonge lentement bras et jambe opposés puis reviens sans bouger le bassin.',goal:'Contrôle du tronc et du bassin.',avoid:'Bas du dos qui se soulève.'},
  {name:'Step-down latéral',kind:'Trail',family:'trail',sheet:4,art:'p0',sets:3,reps:8,cue:'Descente lente depuis une marche basse.',explain:'Effleure le talon au sol puis remonte avec la jambe sur le support.',goal:'Quadriceps et contrôle des descentes.',avoid:'Laisser le genou s’effondrer vers l’intérieur.'},
  {name:'Soulevé de terre une jambe kettlebell',kind:'Kettlebell',family:'trail',sheet:4,art:'p1',sets:3,reps:8,cue:'Hanches carrées, jambe libre tendue derrière.',explain:'Bascule depuis les hanches et remonte en gardant l’équilibre sur une jambe.',goal:'Ischios, fessiers et stabilité.',avoid:'Tourner le bassin ou chercher trop bas.'},
  {name:'Pont fessier',kind:'Poids du corps',family:'general',sheet:4,art:'p2',sets:3,reps:12,cue:'Pieds proches des fessiers.',explain:'Pousse dans les talons, serre les fessiers en haut puis redescends lentement.',goal:'Fessiers et chaîne postérieure.',avoid:'Hypercambrer en haut du mouvement.'},
  {name:'Relevés tibiaux au mur',kind:'Trail',family:'trail',sheet:4,art:'p3',sets:3,reps:15,cue:'Dos au mur, talons au sol.',explain:'Relève les orteils vers les tibias puis repose-les en contrôle.',goal:'Tibias et protection des descentes.',avoid:'Décoller les talons ou aller trop vite.'},
  {name:'Chaise au mur',kind:'Poids du corps',family:'trail',sheet:4,art:'p4',sets:3,reps:30,unit:'sec',cue:'Dos au mur, cuisses proches de l’horizontale.',explain:'Respire et répartis le poids sur tout le pied.',goal:'Endurance des quadriceps.',avoid:'Douleur vive au genou ou position trop profonde.'},
  {name:'Squat cosaque',kind:'Poids du corps',family:'trail',sheet:4,art:'p5',sets:3,reps:6,cue:'Une hanche descend, autre jambe longue.',explain:'Déplace le poids latéralement avec un pied ancré et un buste fier.',goal:'Mobilité latérale et adducteurs.',avoid:'Forcer la profondeur si la hanche tire.'},
  {name:'Pike push-up',kind:'Poids du corps',family:'general',sheet:5,art:'p0',sets:3,reps:6,cue:'Hanches hautes, tête vers le sol.',explain:'Plie les bras pour amener le sommet du crâne près du sol puis repousse.',goal:'Épaules et triceps.',avoid:'Écraser la nuque ou perdre le contrôle des épaules.'},
  {name:'Rowing kettlebell un bras',kind:'Kettlebell',family:'general',sheet:5,art:'p1',sets:3,reps:10,cue:'Dos long, épaule loin de l’oreille.',explain:'Tire le coude vers la hanche, marque une pause puis redescends lentement.',goal:'Dos et stabilité de l’épaule.',avoid:'Tourner le buste ou tirer avec l’épaule vers le haut.'},
  {name:'Développé militaire kettlebell',kind:'Kettlebell',family:'general',sheet:5,art:'p2',sets:3,reps:8,cue:'Fessiers serrés, poignet neutre.',explain:'Presse la kettlebell au-dessus de la tête sans cambrer.',goal:'Épaules, triceps et gainage debout.',avoid:'Douleur à l’épaule ou dos qui se creuse.'},
  {name:'Floor press kettlebell',kind:'Kettlebell',family:'general',sheet:5,art:'p3',sets:3,reps:10,cue:'Coude touche légèrement le sol.',explain:'Allongé au sol, pousse la kettlebell vers le plafond puis redescends avec contrôle.',goal:'Pectoraux et triceps avec amplitude sécurisée.',avoid:'Verrouiller brutalement le coude.'},
  {name:'Bird dog',kind:'Poids du corps',family:'core',sheet:5,art:'p4',sets:3,reps:10,cue:'Main et genou opposés ancrés.',explain:'Allonge bras et jambe opposés sans faire tourner le bassin.',goal:'Stabilité lombaire et coordination.',avoid:'Chercher haut au prix d’un dos qui se creuse.'},
  {name:'Superman',kind:'Poids du corps',family:'core',sheet:5,art:'p5',sets:3,reps:12,cue:'Regard vers le sol, nuque longue.',explain:'Soulève légèrement bras et jambes, marque une pause puis relâche.',goal:'Endurance douce du dos.',avoid:'Forcer une grande extension lombaire.'}
];
const programs = {
  fullbody: { name:'Force trail sans salle', desc:'3 séances de 35–50 min · KB · gilet · poids du corps', days:['A · Force de base','B · Jambes & poussée','C · Trail & tronc'], workouts:[
    {title:'A · Force de base',duration:50,why:'Le socle trail : jambes, poussée, chaîne postérieure, dos et tronc.',exercises:[{name:'Goblet squat kettlebell',sets:3,reps:8},{name:'Pompes inclinées',sets:3,reps:8},{name:'Soulevé de terre kettlebell',sets:3,reps:10},{name:'Rowing kettlebell un bras',sets:3,reps:10},{name:'Gainage planche',sets:3,reps:30}]},
    {title:'B · Jambes & poussée',duration:45,why:'Unilatéral, stabilité et haut du corps sans aller à l’échec.',exercises:[{name:'Split squat bulgare',sets:3,reps:8},{name:'Pompes classiques',sets:3,reps:8},{name:'Step-up gilet',sets:3,reps:10},{name:'Élévations mollets',sets:3,reps:15},{name:'Bird dog',sets:3,reps:10}]},
    {title:'C · Trail & tronc',duration:40,why:'Force utile en montée, contrôle de descente, mollets et gainage.',exercises:[{name:'Step-down latéral',sets:3,reps:8},{name:'Kettlebell swing',sets:3,reps:12},{name:'Relevés tibiaux au mur',sets:3,reps:15},{name:'Gainage latéral',sets:3,reps:25},{name:'Dead bug',sets:3,reps:10}]}
  ]},
  ppl: { name:'Circuit athlète', desc:'2–3 séances adaptables · sans chercher l’épuisement', days:['Jambes + tronc','Haut du corps','Circuit facile'], workouts:[
    {title:'Jambes + tronc',duration:45,why:'Contrôle, amplitude et force utilisable au quotidien.',exercises:[{name:'Goblet squat kettlebell',sets:3,reps:10},{name:'Fentes arrière',sets:3,reps:8},{name:'Pont fessier',sets:3,reps:12},{name:'Élévations mollets',sets:3,reps:15},{name:'Hollow hold',sets:3,reps:20}]},
    {title:'Haut du corps',duration:45,why:'Poussée, tirage et stabilité d’épaules équilibrés.',exercises:[{name:'Pompes inclinées',sets:3,reps:10},{name:'Rowing kettlebell un bras',sets:3,reps:10},{name:'Développé militaire kettlebell',sets:3,reps:8},{name:'Floor press kettlebell',sets:3,reps:10},{name:'Marche fermier kettlebell',sets:3,reps:30}]},
    {title:'Circuit facile',duration:30,why:'Bouger sans entamer la récupération.',exercises:[{name:'Step-up gilet',sets:3,reps:8},{name:'Mountain climbers',sets:3,reps:20},{name:'Kettlebell swing',sets:3,reps:10},{name:'Dead bug',sets:3,reps:10}]}
  ]},
  run: { name:'Base ultra-trail', desc:'Force trail autour des sorties faciles', days:['Force courte','Côtes & mollets','Tronc & mobilité'], workouts:[
    {title:'Force courte trail',duration:40,why:'À placer loin de la sortie longue : peu d’exercices, bien faits.',exercises:[{name:'Step-up gilet',sets:3,reps:10},{name:'Soulevé de terre une jambe kettlebell',sets:3,reps:8},{name:'Élévations mollets',sets:3,reps:15},{name:'Relevés tibiaux au mur',sets:3,reps:15},{name:'Gainage planche',sets:3,reps:30}]},
    {title:'Côtes & mollets',duration:35,why:'Tolérance aux montées et aux descentes, sans finir vidé.',exercises:[{name:'Split squat bulgare',sets:3,reps:8},{name:'Step-down latéral',sets:3,reps:8},{name:'Élévations mollets',sets:4,reps:12},{name:'Chaise au mur',sets:3,reps:30},{name:'Gainage latéral',sets:3,reps:25}]},
    {title:'Tronc & mobilité',duration:30,why:'Une séance légère qui protège la régularité.',exercises:[{name:'Dead bug',sets:3,reps:10},{name:'Hollow hold',sets:3,reps:20},{name:'Bear crawl',sets:3,reps:20},{name:'Bird dog',sets:3,reps:10},{name:'Gainage planche',sets:2,reps:30}]}
  ]}
};

