/*
 * renderer-smoke.cjs — vérifie que index.html + app.js se chargent SANS erreur JS
 * dans un vrai renderer Electron (ce qu'un simple "le process tourne encore" ne détecte pas).
 * Sortie : code 0 = OK, code 1 = échec (avec détail).
 * Lancé via `npm run test:smoke`.
 */
const { app, BrowserWindow, ipcMain } = require('electron');
const path = require('path');

// Stubs des canaux IPC attendus par preload/app.js (sinon rejets non gérés parasites).
ipcMain.handle('app:version', () => '0.0.0-test');
ipcMain.handle('calendar:fetch', () => ({ ok: false, error: 'stub' }));
ipcMain.handle('calendar:subs:get', () => []);
ipcMain.handle('calendar:subs:save', (_e, l) => l);
ipcMain.handle('notifications:get', () => ({ enabled: false, times: ['09:00', '18:00'], lastSent: {}, leadMinutes: 15, eveningTime: '21:00', eveningEnabled: true }));
ipcMain.handle('notifications:save', (_e, v) => v);
ipcMain.handle('notifications:test', () => true);
ipcMain.handle('backup:save', () => true);
ipcMain.handle('backup:get', () => null);
ipcMain.handle('photos:save', (_e, p) => ({ id: (p && p.id) || 1, file: `${(p && p.id) || 1}.png` }));
ipcMain.handle('photos:read', () => null);
ipcMain.handle('photos:delete', () => true);
ipcMain.handle('travel:config:get', () => ({ home: '', mode: 'driving' }));
ipcMain.handle('travel:config:save', (_e, v) => v);
ipcMain.handle('travel:estimate', () => ({ ok: false, error: 'stub' }));
ipcMain.handle('update:check', () => ({ ok: true }));
ipcMain.handle('update:install', () => true);
ipcMain.handle('data:export', () => ({ ok: false, canceled: true }));
ipcMain.handle('data:import', () => ({ ok: false, canceled: true }));

const errors = [];
app.disableHardwareAcceleration();

app.whenReady().then(async () => {
  const win = new BrowserWindow({
    show: false,
    webPreferences: {
      preload: path.join(__dirname, '..', 'preload.cjs'),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true
    }
  });
  win.webContents.on('console-message', (_e, level, message) => {
    if (level >= 3 || /uncaught|is not defined|is not a function|\[IRL\]/i.test(message)) {
      errors.push('console: ' + message);
    }
  });
  win.webContents.on('render-process-gone', (_e, d) => errors.push('render-process-gone: ' + d.reason));
  win.webContents.on('did-fail-load', (_e, code, desc) => errors.push('did-fail-load: ' + desc));

  const bail = setTimeout(() => { console.error('SMOKE TIMEOUT (15s)'); app.exit(1); }, 15000);

  try {
    await win.loadFile(path.join(__dirname, '..', 'index.html'));
    await new Promise(r => setTimeout(r, 900)); // laisse app.js finir (onboarding, restore...)
    const checks = await win.webContents.executeJavaScript(`(function(){
      return {
        logicLoaded: typeof localDate === 'function' && typeof pct === 'function' && typeof computeStreak === 'function' && typeof normalizeAgendaItem === 'function',
        normalize: typeof normalizeState === 'function',
        photosApi: typeof loadGalleryPhotos === 'function' && typeof migratePhotosToDisk === 'function' && !!(window.desktop && window.desktop.savePhoto),
        photoCompare: typeof photoComparePair === 'function' && !!document.getElementById('photoCompare') && (() => { const c = photoComparePair([{ date: '2026-05-01', file: 'a' }, { date: '2026-07-10', file: 'b' }], [{ date: '2026-05-02', value: 84 }, { date: '2026-07-09', value: 79 }]); return c && c.before.date === '2026-05-01' && c.after.date === '2026-07-10' && c.weightDelta === -5 && photoComparePair([{ date: '2026-05-01' }]) === null; })(),
        studyPlanner: !!document.getElementById('studyPlanForm') && typeof planStudySessions === 'function' && typeof buildIcs === 'function',
        examCountdown: typeof examCountdown === 'function' && typeof renderExamCountdown === 'function' && !!document.getElementById('examCountdown') && examCountdown({ title: 'BTS', date: '2099-01-11' }, '2099-01-01').daysLeft === 10,
        studyProgress: typeof studyStats === 'function' && !!document.getElementById('studyProgress') && (s => s.total === 2 && s.done === 1 && s.upcoming === 1)(studyStats([{ kind: 'study', date: '2026-07-05', completed: true }, { kind: 'study', date: '2099-07-12', completed: false }], '2026-07-10')),
        studyPacing: typeof studyPacing === 'function' && !!document.getElementById('studyPacing') && (() => { const exam = { date: '2026-08-10' }; const agenda = [{ kind: 'study', date: '2026-07-06', completed: true }, { kind: 'study', date: '2026-07-16', completed: false }, { kind: 'study', date: '2026-07-20', completed: false }, { kind: 'study', date: '2026-07-25', completed: false }]; const p = studyPacing(agenda, exam, '2026-07-13'); return p.remaining === 3 && p.daysLeft === 28 && p.perWeek === 1 && p.status === 'ahead' && studyPacing([], exam, '2026-07-13') === null && studyPacing(agenda, null, '2026-07-13') === null; })(),
        overdueStudy: typeof overdueStudy === 'function' && !!document.getElementById('overdueStudy') && (() => { const r = overdueStudy([{ kind: 'study', date: '2026-07-13', title: 'Compta', completed: false }, { kind: 'study', date: '2026-07-12', title: 'Faite', completed: true }, { kind: 'study', date: '2026-07-20', title: 'Future', completed: false }], '2026-07-15'); return r.length === 1 && r[0].title === 'Compta' && r[0].daysLate === 2 && overdueStudy(null, '2026-07-15').length === 0; })(),
        examReminder: typeof examReminderDue === 'function' && /demain/.test(examReminderDue({ title: 'BTS', date: '2026-05-15' }, '2026-05-14')) && examReminderDue({ date: '' }, '2026-05-14') === null,
        myDay: !!document.getElementById('myDayList') && typeof todayItems === 'function' && !!(document.getElementById('myDaySummary') || {}).textContent,
        charts: !!document.getElementById('chartGrid') && typeof weeklyAggregate === 'function' && typeof renderCharts === 'function',
        weekView: !!document.getElementById('weekGrid') && typeof weekItems === 'function' && typeof renderWeekPage === 'function' && !!document.getElementById('openWeekPage'),
        monthDayJump: typeof renderMonthCalendar === 'function' && (() => { renderMonthCalendar(); return document.querySelectorAll('#monthCalendar .month-day[data-cal-day]').length >= 28; })(),
        keyDateMarkers: typeof keyDateMarkers === 'function' && keyDateMarkers({ title: 'BTS', date: '2026-05-15' }, { date: '2026-06-01' }, '2026-05-15')[0].kind === 'exam' && keyDateMarkers(null, null, '2026-05-15').length === 0,
        upcomingDeadlines: typeof upcomingKeyDates === 'function' && !!document.getElementById('upcomingDeadlines') && (r => r.length === 2 && r[0].kind === 'race')(upcomingKeyDates({ date: '2026-07-25' }, { date: '2026-07-15' }, '2026-07-10', 60)),
        priorityDeadlines: typeof upcomingPriorityItems === 'function' && (() => { const r = upcomingPriorityItems([{ kind: 'study', priority: 'high', date: '2026-07-20', title: 'Rendu', completed: false }, { kind: 'life', priority: 'high', date: '2026-07-13', title: 'Contrôle', completed: false }, { kind: 'sport', priority: 'normal', date: '2026-07-12', title: 'X', completed: false }], '2026-07-10', 30, 3); return r.length === 2 && r[0].title === 'Contrôle' && r[0].daysLeft === 3; })(),
        printReport: !!document.getElementById('printReport') && typeof weeklySummary === 'function' && typeof renderPrintReport === 'function' && !!document.getElementById('printWeekReport'),
        weeklyText: typeof weeklySummaryText === 'function' && !!document.getElementById('copyWeeklySummary') && /3 séances/.test(weeklySummaryText({ sessions: 3, minutes: 150 })),
        weeklyShare: typeof shareableWeek === 'function' && !!document.getElementById('shareWeeklySummary') && (() => { const s = shareableWeek({ mondayKey: '2026-07-06', sessions: 3, minutes: 150 }); return s && /bilan de la semaine/i.test(s.title) && s.text === weeklySummaryText({ mondayKey: '2026-07-06', sessions: 3, minutes: 150 }); })(),
        monthlyRecap: typeof monthlyRecap === 'function' && typeof monthLabelFr === 'function' && !!document.getElementById('monthlyRecap') && !!document.getElementById('copyMonthlyRecap') && (() => { const r = monthlyRecap({ workouts: [{ date: '2026-07-03', type: 'run', duration: 40, distance: 8 }], focusSessions: [{ date: '2026-07-05', minutes: 25 }] }, '2026-07'); return r && r.sessions === 1 && r.km === 8 && r.activeDays === 2 && monthLabelFr('2026-07') === 'juillet 2026' && monthlyRecap({}, '2020-01') === null; })(),
        monthlyShare: typeof shareableMonth === 'function' && !!document.getElementById('shareMonthlyRecap') && (() => { const r = { monthKey: '2026-07', sessions: 3, minutes: 150, activeDays: 4 }; const s = shareableMonth(r); return s && /Mon bilan de juillet 2026/.test(s.title) && s.text === monthlyRecapText(r) && shareableMonth(null) === null; })(),
        weeklyInsights: typeof weeklyInsights === 'function' && !!document.getElementById('weeklyInsights') && (() => { const ins = weeklyInsights({ workouts: [{ date: '2026-07-06', type: 'strength', duration: 50, effort: 3 }], goals: { sessions: 4 } }, '2026-07-06', '2026-07-11'); return Array.isArray(ins) && ins.length >= 1 && ins.every(i => i.emoji && i.text && i.tone); })(),
        theme: !!document.getElementById('themeToggle') && (getComputedStyle(document.documentElement).getPropertyValue('--surface-2').trim().length > 0),
        themeAuto: typeof nextThemeMode === 'function' && typeof resolveTheme === 'function' && nextThemeMode('auto') === 'light' && resolveTheme('auto', true) === 'dark' && typeof applyTheme === 'function' && typeof currentThemeMode === 'function',
        themeTime: typeof nextThemeMode === 'function' && nextThemeMode('dark') === 'time' && nextThemeMode('time') === 'auto' && resolveTheme('time', false, 14) === 'light' && resolveTheme('time', false, 22) === 'dark' && resolveTheme('time', true) === 'dark',
        raceGoal: !!document.getElementById('raceGoalType') && typeof raceGoalStatus === 'function' && typeof renderRaceGoal === 'function',
        nextSession: typeof nextTrainingSession === 'function' && !!document.getElementById('nextSessionLine') && (nextTrainingSession([{ id: 1, date: '2999-01-02', time: '10:00', type: 'X' }], '2999-01-01', 0) || {}).daysLeft === 1,
        weekStreak: typeof weeklyWorkoutStreak === 'function' && !!document.getElementById('weekStreakBadge') && weeklyWorkoutStreak([{ date: '2026-07-08' }, { date: '2026-07-01' }], '2026-07-10') === 2,
        completeDaysStreak: typeof completeDaysStreak === 'function' && !!document.getElementById('missionStreak') && (() => { const days = [{ date: '2026-07-10', count: 5 }, { date: '2026-07-09', count: 4 }, { date: '2026-07-08', count: 6 }, { date: '2026-07-07', count: 2 }]; return completeDaysStreak(days, 4, '2026-07-10') === 3 && completeDaysStreak(days, 6, '2026-07-10') === 0 && completeDaysStreak([], 4, '2026-07-10') === 0; })(),
        heatmap: typeof trainingHeatmap === 'function' && !!document.getElementById('trainingHeatmap') && trainingHeatmap([], '2026-07-10', 8).length === 56 && trainingHeatmap([{ date: '2026-07-08' }], '2026-07-10', 1)[2].count === 1,
        loadAdvice: typeof loadAdvice === 'function' && !!document.getElementById('loadAdvice') && loadAdvice({ zone: 'high' }, { score: 90 }).status === 'deload' && loadAdvice({ zone: 'optimal' }, { score: 80 }).status === 'push' && loadAdvice(null, null).status === 'maintain',
        missedSessions: typeof missedSessions === 'function' && !!document.getElementById('missedSessions') && (() => { const m = missedSessions([{ kind: 'sport', date: '2026-07-13', title: 'S', completed: false }, { kind: 'sport', date: '2026-07-12', title: 'S2', completed: true }], [], '2026-07-15', { days: 14 }); return m.length === 1 && m[0].date === '2026-07-13' && missedSessions([], [], 'x').length === 0; })(),
        acwr:typeof acuteChronicRatio === 'function' && (r => r && r.ratio === 1 && r.zone === 'optimal')(acuteChronicRatio([{ date: '2026-07-08', duration: 60, effort: 2 }, { date: '2026-06-30', duration: 60, effort: 2 }, { date: '2026-06-23', duration: 60, effort: 2 }, { date: '2026-06-17', duration: 60, effort: 2 }], '2026-07-10')),
        focusStreak: typeof dailyStreak === 'function' && dailyStreak(['2026-07-10', '2026-07-09', '2026-07-08'], '2026-07-10') === 3,
        recentWins: typeof recentWins === 'function' && !!document.getElementById('recentWins') && (() => { const r = recentWins([{ date: '2026-07-08', win: 'A' }, { date: '2026-07-09', win: 'B' }, { date: '2026-07-10', win: 'Aujourdhui' }, { date: '2026-07-07', win: '  ' }], '2026-07-10'); return r.length === 2 && r[0].win === 'B' && r[0].daysAgo === 1 && recentWins(null, '2026-07-10').length === 0; })(),
        focusOutcomes: typeof recentFocusOutcomes === 'function' && !!document.getElementById('focusOutcomes') && (() => { const rv = [{ id: 1, date: '2026-07-08', outcome: 'A' }, { id: 2, date: '2026-07-10', outcome: 'B' }, { id: 3, date: '2026-07-10', outcome: 'C' }, { id: 4, date: '2026-07-09', outcome: '  ' }]; const r = recentFocusOutcomes(rv, '2026-07-10'); return r.length === 3 && r[0].outcome === 'C' && r[0].daysAgo === 0 && r[2].outcome === 'A' && recentFocusOutcomes(null, '2026-07-10').length === 0; })(),
        recentLessons: typeof recentLessons === 'function' && !!document.getElementById('recentLessons') && (() => { const refl = [{ date: '2026-07-08', win: 'V', lesson: 'L1' }, { date: '2026-07-09', lesson: 'L2' }, { date: '2026-07-07', win: 'Sans lecon' }]; const r = recentLessons(refl, '2026-07-10'); return r.length === 2 && r[0].lesson === 'L2' && r[0].daysAgo === 1 && recentWins(refl, '2026-07-10').length === 2 && recentLessons(null, '2026-07-10').length === 0; })(),
        focusWeekGoal: typeof focusWeekGoal === 'function' && !!document.getElementById('focusWeekGoal') && (() => { const g = focusWeekGoal([{ date: '2026-07-13', minutes: 25 }, { date: '2026-07-14', minutes: 50 }], '2026-07-15', 120); return g && g.done === 75 && g.target === 120 && g.remaining === 45 && g.status === 'onTrack' && focusWeekGoal([], 'x', 120) === null; })(),
        focusHeatmap: !!document.getElementById('focusHeatmap') && document.querySelectorAll('#focusHeatmap .hm-cell').length === 56,
        supplements: !!document.getElementById('suppHeat') && typeof hydrationPlan === 'function' && !!(document.getElementById('suppProteinTarget') || {}).textContent,
        nutritionPlus: typeof supplementTiming === 'function' && typeof searchFoods === 'function' && !!document.getElementById('foodResults') && (document.querySelectorAll('#suppTimingGrid .supp-phase').length >= 3),
        foodLogProt: typeof bumpProtein === 'function' && typeof searchFoods === 'function' && searchFoods('', 12).some(x => x.p > 0),
        hydration: typeof waterStatus === 'function' && !!document.getElementById('waterPlus') && !!document.getElementById('waterMinus') && !!document.getElementById('hydraFill') && !!document.getElementById('proteinFill') && typeof proteinTarget === 'function',
        proteinQuick: !!document.getElementById('proteinPlus20') && !!document.getElementById('proteinPlus30') && !!document.getElementById('proteinMinus'),
        proteinSnack: typeof proteinSnackSuggestion === 'function' && !!document.getElementById('proteinSnack') && (() => { const r = proteinSnackSuggestion(120, 150); return r.gap === 30 && r.snackProtein === 30 && proteinSnackSuggestion(148, 150) === null && proteinSnackSuggestion(50, 0) === null; })(),
        waterGoalAdaptive: typeof waterGoalFor === 'function' && waterGoalFor(8, true) === 10 && waterGoalFor(8, false) === 8,
        proteinWeek: typeof proteinDaysOnTarget === 'function' && proteinDaysOnTarget([{ date: '2026-07-06', protein: 160 }, { date: '2026-07-09', protein: 130 }], 130, '2026-07-06', '2026-07-10') === 2,
        waterWeek: typeof daysHittingTarget === 'function' && daysHittingTarget([{ date: '2026-07-06', water: 8 }, { date: '2026-07-07', water: 5 }], 'water', 8, '2026-07-06', '2026-07-10') === 1,
        proteinTargetUnified: typeof proteinTarget === 'function' && (() => { const t = proteinTarget(state.profile.weight, state.profile.goal).gramsPerDay; const s = (document.getElementById('nutritionStatus') || {}).textContent || ''; return t === 145 && (s.includes(String(t)) || /\d/.test(s)); })(),
        sleepDebt: typeof sleepDebtHours === 'function' && (r => r.debt === 3.5 && r.nights === 3)(sleepDebtHours([{ date: '2026-07-06', sleep: 6 }, { date: '2026-07-07', sleep: 8 }, { date: '2026-07-08', sleep: 5.5 }], 7.5, '2026-07-06', '2026-07-10')),
        weeklySleep: typeof weeklySleepStats === 'function' && !!document.getElementById('weeklySleep') && (() => { const r = weeklySleepStats([{ date: '2026-07-06', sleep: 6 }, { date: '2026-07-07', sleep: 8 }, { date: '2026-07-08', sleep: 5.5 }], '2026-07-06', '2026-07-10'); return r.nights === 3 && r.avg === 6.5 && r.min === 5.5 && r.status === 'court' && weeklySleepStats([], '2026-07-06', '2026-07-10') === null; })(),
        readiness: typeof readinessScore === 'function' && !!document.getElementById('recoveryScore') && readinessScore({ sleep: 8, fatigue: 1, soreness: 1 }).score === 100 && readinessScore(null) === null,
        readinessTrend: typeof readinessTrend === 'function' && !!document.getElementById('readinessTrend') && (() => { const rt = readinessTrend([{ date: '2026-07-06', sleep: 5, fatigue: 4, soreness: 4 }, { date: '2026-07-10', sleep: 8, fatigue: 1, soreness: 1 }], 8); return rt && rt.points.length === 2 && rt.delta === 60 && rt.direction === 'up' && readinessTrend([], 8) === null; })(),
        morningEnergy: typeof morningEnergyTrend === 'function' && !!document.getElementById('morningEnergyTrend') && (() => { const t = morningEnergyTrend([{ date: '2026-07-14', energy: 2 }, { date: '2026-07-12', energy: 3 }, { date: '2026-07-09', energy: 3 }, { date: '2026-07-05', energy: 4 }, { date: '2026-07-02', energy: 4 }], '2026-07-14', 7); return t && t.count === 3 && t.avg === 2.7 && t.prevAvg === 4 && t.dir === 'down' && t.level === 'low' && morningEnergyTrend([], '2026-07-14', 7) === null; })(),
        records: typeof personalRecords === 'function' && !!document.getElementById('exerciseDetailNotes'),
        newRecordToast: typeof newRecords === 'function' && typeof flashToast === 'function' && newRecords({ T: { load: 0, reps: 8 } }, { T: { load: 0, reps: 10 } }).length === 1,
        strengthRecords: typeof strengthRecords === 'function' && typeof nextStrengthMilestone === 'function' && !!document.getElementById('strengthRecords') && (() => { const r = strengthRecords([{ date: '2026-06-08', exercises: [{ name: 'DC', load: 45, reps: 5 }, { name: 'Sq', load: 60, reps: 10 }] }]); const nm = nextStrengthMilestone(133.5, 10); return r.length === 2 && r[0].name === 'Sq' && r[0].e1rm === 80 && strengthRecords([]).length === 0 && nm.milestone === 140 && nm.gap === 6.5; })(),
        exerciseHistory: typeof exerciseHistoryStats === 'function' && (() => { const h = exerciseHistoryStats([{ date: '2026-06-01', exercises: [{ name: 'DC', load: 40, reps: 8, sets: 3 }] }, { date: '2026-06-10', exercises: [{ name: 'DC', load: 42.5, reps: 6, sets: 3 }] }], 'DC'); return h && h.sessions === 2 && h.lastDate === '2026-06-10' && h.bestSet.load === 42.5 && exerciseHistoryStats([], 'X') === null; })(),
        repeatLast: typeof lastLoggedSession === 'function' && !!document.getElementById('repeatLastSession') && lastLoggedSession([{ type: 'strength', date: '2026-07-08', exercises: [{ name: 'T' }] }]).date === '2026-07-08',
        exportTsv: typeof workoutsTable === 'function' && !!document.getElementById('exportHistoryTsv') && workoutsTable([{ date: '2026-07-08', type: 'run', duration: 30 }]).split(String.fromCharCode(10)).length === 2,
        historyExFilter: typeof workoutsWithExercise === 'function' && !!document.getElementById('historyExercise') && (() => { const w = [{ id: 1, exercises: [{ name: 'Tractions' }] }, { id: 2, exercise: 'Squat' }]; return workoutsWithExercise(w, 'Tractions').length === 1 && workoutsWithExercise(w, 'all').length === 2 && workoutsWithExercise(w, 'Inconnu').length === 0; })(),
        progSpark: typeof exerciseVolumeSeries === 'function' && (s => s.length === 2 && s[1].volume === 150)(exerciseVolumeSeries([{ name: 'T', date: '2026-06-01', volume: 100 }, { name: 'T', date: '2026-06-03', volume: 150 }], 'T', 8)),
        oneRepMax: typeof estimate1RM === 'function' && estimate1RM(100, 10) === 133.5 && estimate1RM(100, 1) === 100 && estimate1RM(0, 5) === null,
        oneRmSeries: typeof estimatedOneRmSeries === 'function' && (() => { const s = estimatedOneRmSeries([{ date: '2026-06-01', exercises: [{ name: 'DC', load: 40, reps: 8 }] }, { date: '2026-06-08', exercises: [{ name: 'DC', load: 50, reps: 3 }] }], 'DC', 8); return s.length === 2 && s[1].e1rm === 55 && estimatedOneRmSeries([], 'DC', 8).length === 0; })(),
        progression: typeof progressionSuggestion === 'function' && typeof progressionText === 'function' && (() => { const s = progressionSuggestion([{ date: '2026-06-08', exercises: [{ name: 'DC', load: 40, reps: 12 }] }], 'DC', { minReps: 8, maxReps: 12, increment: 2.5 }); return s && s.action === 'weight' && s.nextLoad === 42.5 && s.nextReps === 8 && /42,5 kg/.test(progressionText(s)) && progressionSuggestion([], 'X') === null; })(),
        loadPercentages: typeof loadPercentages === 'function' && (() => { const r = loadPercentages(100); return r.length === 4 && r[2].pct === 80 && r[2].load === 80 && loadPercentages(0).length === 0; })(),
        guidedTarget: !!document.getElementById('guidedTarget') && typeof progressionSuggestion === 'function' && (() => { const s = progressionSuggestion([{ date: '2026-06-08', exercises: [{ name: 'DC', load: 40, reps: 9 }] }], 'DC', { minReps: 8, maxReps: 12, increment: 2.5 }); return s && s.nextReps === 10 && s.nextLoad === 40; })(),
        pace: typeof runPace === 'function' && runPace(10, 50).label === '5:00' && runPace(0, 30) === null,
        sessionTime: typeof sessionMinutes === 'function' && sessionMinutes([8, 10, 12]) === 30 && !!document.getElementById('guidedSessionTime'),
        runVolumeWow: typeof runKmInWindow === 'function' && runKmInWindow([{ type: 'run', date: '2026-07-06', distance: 10 }, { type: 'run', date: '2026-07-09', distance: 5.5 }], '2026-07-06', '2026-07-12') === 15.5,
        trailReadiness: typeof trailReadiness === 'function' && !!document.getElementById('trailRunSummary') && (() => { const tr = trailReadiness([{ type: 'run', date: '2026-07-08', distance: 12 }, { type: 'run', date: '2026-06-20', distance: 21 }], '2026-07-10'); return tr && tr.weekKm === 12 && tr.monthKm === 33 && tr.runs === 2 && tr.longRun.km === 21 && trailReadiness([], '2026-07-10') === null; })(),
        kmRamp: typeof weeklyKmRamp === 'function' && !!document.getElementById('trailRamp') && (() => { const rm = weeklyKmRamp([{ type: 'run', date: '2026-07-08', distance: 25 }, { type: 'run', date: '2026-07-01', distance: 20 }], '2026-07-10'); return rm && rm.thisWeekKm === 25 && rm.lastWeekKm === 20 && rm.rampPct === 25 && rm.zone === 'build' && weeklyKmRamp([], '2026-07-10') === null; })(),
        tonnage: typeof workoutTonnage === 'function' && workoutTonnage({ exercises: [{ load: 60, reps: 10, sets: 3 }] }) === 1800 && workoutTonnage({ exercises: [{ setLogs: [{ load: 40, reps: 8, completed: true }, { load: 40, reps: 6 }] }] }) === 320 && workoutTonnage(null) === 0,
        guidedStats: typeof completedTonnage === 'function' && typeof completedSetCount === 'function' && !!document.getElementById('guidedSessionStats') && (() => { const ex = [{ setLogs: [{ load: 40, reps: 8, completed: true }, { load: 40, reps: 6, completed: false }] }, { setLogs: [{ load: 60, reps: 10, completed: true }] }]; return completedTonnage(ex) === 920 && completedSetCount(ex) === 2 && completedTonnage([]) === 0; })(),
        sessionRecap: typeof sessionSummary === 'function' && !!document.getElementById('guidedRecap') && (() => { const s = sessionSummary([{ name: 'DC', setLogs: [{ load: 40, reps: 8, completed: true }] }], { DC: { load: 35, reps: 8 } }); return s.tonnage === 320 && s.sets === 1 && s.exercises === 1 && s.prs.length === 1 && s.prs[0].loadPr; })(),
        weightTrend: typeof weightTrend === 'function' && !!document.getElementById('weightTrend') && (t => t && t.ratePerWeek === -0.5 && t.weeksToTarget === 4)(weightTrend([{ date: '2026-06-26', value: 82 }, { date: '2026-07-10', value: 81 }], 79)),
        coachWeight: typeof energyPlan === 'function' && typeof basalMetabolicRate === 'function' && !!document.getElementById('coachWeightBody') && !!document.getElementById('coachAge') && (() => { const p = energyPlan({ weight: 80, height: 180, age: 30, sex: 'homme', sessionsPerWeek: 4, targetWeight: 72, todayKey: '2026-07-12' }); return p && p.bmr === 1780 && p.tdee === 2759 && p.goal === 'perte' && p.weeks === 17 && p.targetDate === '2026-11-08' && energyPlan({ weight: 80, height: 180, age: 30, targetWeight: 0 }) === null; })(),
        coachBmi: typeof bmiInfo === 'function' && (() => { const b = bmiInfo(80, 180); return b && b.bmi === 24.7 && b.category === 'corpulence normale' && bmiInfo(0, 180) === null; })(),
        lifetimeTonnage: typeof lifetimeTonnage === 'function' && lifetimeTonnage([{ exercises: [{ name: 'Sq', load: 60, reps: 10, sets: 3 }] }, { exercises: [{ name: 'DC', setLogs: [{ load: 40, reps: 8, completed: true }] }] }]) === 2120 && lifetimeTonnage([]) === 0,
        strengthPlateau: typeof strengthPlateau === 'function' && strengthPlateau([90, 92, 94, 96, 98], 3) === null && (() => { const p = strengthPlateau([95, 100, 98, 99, 97], 3); return p && p.plateau === true && p.best === 100; })(),
        strengthForecast: typeof strengthForecast === 'function' && (() => { const f = strengthForecast([{ date: '2026-06-08', e1rm: 90 }, { date: '2026-06-22', e1rm: 95 }], 5, '2026-06-22'); return f && f.milestone === 100 && f.perWeek === 2.5 && strengthForecast([{ date: '2026-06-08', e1rm: 90 }, { date: '2026-06-22', e1rm: 90 }], 5) === null; })(),
        coachForecast: typeof weightForecast === 'function' && typeof coachForecastSvg === 'function' && (() => { const f = weightForecast(80, 72, 0.48, 17, '2026-07-12'); const svg = coachForecastSvg(f, [{ date: '2026-07-05', value: 81 }, { date: '2026-07-12', value: 80 }]); return f.length === 18 && f.at(-1).value === 72 && /cw-plan-line/.test(svg) && /cw-actual-line/.test(svg) && weightForecast(80, 72, 0, 17, '2026-07-12').length === 0; })(),
        coachWeek: typeof coachWeekPlan === 'function' && (() => { const p = coachWeekPlan('perte', [1, 3, 5]); const g = coachWeekPlan('prise', [1, 2, 3, 4, 5, 6]); return p.sessions.length === 3 && p.renfo === 1 && p.runs === 1 && g.strength === 4 && g.sessions.length === 5 && coachWeekPlan('xxx', [1, 3]).note.includes('Maintien'); })(),
        runPlan: typeof runPlanWeek === 'function' && typeof scheduleRunPlan === 'function' && !!document.getElementById('runPlanBtn') && !!document.getElementById('runPlanResult') && (() => { const p = runPlanWeek(4); return p.count === 4 && p.sessions.at(-1).type === 'longue' && p.totalMinutes === 175 && runPlanWeek(99).count === 6; })(),
        coachWeekSchedule: typeof scheduleCoachWeek === 'function' && typeof coachSessionLabel === 'function' && coachSessionLabel('muscu').includes('Musculation') && coachSessionLabel('zzz') === 'Séance',
        coachNutri: typeof mealSplit === 'function' && typeof nutritionTips === 'function' && (() => { const m = mealSplit(2000, 160, 200, 60); return m.length === 4 && m[1].kcal === 700 && m[1].proteinG === 56 && nutritionTips('perte')[0].includes('déficit') && mealSplit(0, 1, 1, 1).length === 0; })(),
        coachMenu: typeof mealIdea === 'function' && (() => { const a = mealIdea('Petit-déjeuner', 500, 0); return a.kcal === 500 && typeof a.example === 'string' && a.example.length > 0 && mealIdea('Déjeuner', 700, 0).example !== mealIdea('Déjeuner', 700, 1).example; })(),
        coachExport: typeof coachPlanText === 'function' && (() => { const t = coachPlanText({ plan: { goal: 'perte', diff: 6, targetDate: '2026-11-08', dailyTarget: 1875, proteinG: 162, carbG: 143, fatG: 73 }, week: [{ weekday: 1, label: 'Course', minutes: 40 }], meals: [{ meal: 'Petit-déjeuner', kcal: 469, example: 'Avoine' }] }); return t.includes('1875 kcal') && t.includes('Course') && coachPlanText({}) === ''; })(),
        coachAdherence: typeof coachSteps === 'function' && typeof weeklyAdherence === 'function' && (() => { const a = weeklyAdherence({ workouts: [{ date: '2026-07-08' }, { date: '2026-07-09' }, { date: '2026-07-10' }], nutrition: [{ date: '2026-07-08', protein: 150, water: 8 }, { date: '2026-07-09', protein: 150, water: 8 }, { date: '2026-07-10', protein: 150, water: 8 }], recovery: [{ date: '2026-07-09', sleep: 8 }], weights: [{ date: '2026-07-08', value: 80 }] }, '2026-07-06', '2026-07-12', { proteinTargetG: 140, sessionTarget: 3 }); return a.total === 5 && a.score === 100 && coachSteps('perte')[0].includes('déficit'); })(),
        coachAdhHist: typeof upsertAdherenceSnapshot === 'function' && Array.isArray(state.adherenceHistory) && (() => { let h = upsertAdherenceSnapshot([], '2026-07-06', 80); h = upsertAdherenceSnapshot(h, '2026-07-06', 60); h = upsertAdherenceSnapshot(h, '2026-06-29', 40); return h.length === 2 && h[0].week === '2026-06-29' && h[1].score === 60; })(),
        coachRefine: typeof activityLevelFactor === 'function' && typeof dateAfterWeeks === 'function' && typeof paceStatus === 'function' && !!document.getElementById('coachActivity') && activityLevelFactor('actif') === 1.725 && dateAfterWeeks('2026-07-12', 17) === '2026-11-08' && paceStatus(17, 25) === 'slow' && energyPlan({ weight: 80, height: 180, age: 30, sex: 'homme', activityLevel: 'actif', sessionsPerWeek: 2, targetWeight: 72, todayKey: '2026-07-12' }).tdee === 3071,
        coachAdjust: typeof calorieAdjustment === 'function' && (() => { const a = calorieAdjustment([{ date: '2026-06-21', value: 80 }, { date: '2026-07-01', value: 80 }, { date: '2026-07-12', value: 80 }], 'perte', 2000); return a.stagnating && a.suggestion === 'reduce' && a.newTarget === 1875 && calorieAdjustment([{ date: '2026-07-10', value: 80 }, { date: '2026-07-12', value: 80 }], 'perte', 2000).stagnating === false; })(),
        coachMeasure: typeof recompositionInsight === 'function' && recompositionInsight(-0.3, -2).key === 'recomp' && recompositionInsight(-2, -2).key === 'fatloss' && recompositionInsight(-0.2, -0.2) === null,
        measureTrend: typeof measurementDelta === 'function' && !!document.getElementById('measurementsTrend') && (d => d && d.delta === -3)(measurementDelta([{ date: '2026-06-01', waist: 88 }, { date: '2026-07-01', waist: 85 }], 'waist')),
        measureRecent: typeof measurementRecentDelta === 'function' && !!document.getElementById('measurementsRecent') && (() => { const r = measurementRecentDelta([{ date: '2026-04-01', waist: 90 }, { date: '2026-06-01', waist: 88 }, { date: '2026-07-01', waist: 85 }], 'waist', 30); return r && r.past === 88 && r.delta === -3 && r.spanDays === 30 && measurementRecentDelta([{ date: '2026-07-01', waist: 85 }], 'waist', 30) === null; })(),
        kitchen: typeof generateMeals === 'function' && !!document.getElementById('pantryList') && !!document.getElementById('mealSuggestions') && !!document.getElementById('envieStyles'),
        shopping: typeof buildShoppingList === 'function' && !!document.getElementById('shoppingBlock') && !!document.getElementById('shoppingList') && !!document.getElementById('copyShoppingBtn'),
        shoppingCheck: typeof remainingShopping === 'function' && !!document.getElementById('shoppingRemaining') && remainingShopping([{ label: 'a' }, { label: 'b' }], { a: true }) === 1,
        agendaImport: typeof parseIcs === 'function' && !!document.getElementById('importIcs') && !!document.getElementById('importIcsKind') && !!document.getElementById('calendarAgendaPriority'),
        agendaUx: !!document.getElementById('weekQuickAdd') && !!document.getElementById('agendaFilters') && !!document.getElementById('importIcsWeek') && document.querySelectorAll('#agendaFilters [data-filter]').length === 5,
        agendaSearch: typeof agendaMatch === 'function' && !!document.getElementById('agendaSearch'),
        agendaDay: typeof renderDayView === 'function' && typeof renderAgenda === 'function' && !!document.getElementById('dayView') && document.querySelectorAll('#agendaViewSwitch [data-view]').length === 2,
        dayGrid: typeof dayColumns === 'function' && typeof endTimeOf === 'function',
        dayPlanned: typeof dayPlannedMinutes === 'function' && dayPlannedMinutes([{ time: '09:00', durationMin: 60 }, { time: '14:00', durationMin: 90 }]) === 150,
        dayCopy: typeof dayPlanText === 'function' && dayPlanText([{ time: '09:00', title: 'X', completed: true }]) === '- 09:00 X ✓',
        agendaDetails: typeof departureInfo === 'function' && !!document.getElementById('calendarAgendaLocation') && !!document.getElementById('calendarAgendaTravel') && !!document.getElementById('calendarAgendaNotes'),
        agendaEdit: !!document.getElementById('weekQuickLocation') && !!document.getElementById('weekQuickTravel') && !!document.getElementById('weekQuickNotes') && !!document.getElementById('weekQuickEstimate') && !!document.getElementById('agendaEditForm') && !!document.getElementById('editAgendaNotes'),
        agendaDuplicate: typeof duplicateAgendaItem === 'function' && !!document.getElementById('duplicateAgendaEdit') && (duplicateAgendaItem({ id: 1, date: '2026-07-10', planId: 9, completed: true }, 2) || {}).planId === undefined,
        guidedFromPlan: typeof startGuidedFromNames === 'function' && typeof openGuidedWorkout === 'function' && !!document.getElementById('guidedWorkoutDialog'),
        settingsPage: !!document.querySelector('[data-page="settings"]') && !!document.querySelector('.settings-page') && document.querySelectorAll('.settings-conn .conn-row').length === 3 && !!document.getElementById('settingsTheme') && !!document.getElementById('settingsDensity'),
        dataIo: !!document.getElementById('exportDataBtn') && !!document.getElementById('importDataBtn') && !!document.getElementById('dataIoStatus'),
        nutritionCsv: typeof nutritionCsv === 'function' && !!document.getElementById('exportNutritionCsv') && (() => { const csv = nutritionCsv([{ date: '2026-07-06', protein: 150, water: 8, fruit: false }, { date: '2026-07-08', protein: 130, water: 7, fruit: true }]); const lines = csv.split(String.fromCharCode(10)); return lines.length === 3 && lines[0] === 'date,proteines_g,eau_verres,fruits_legumes' && lines[1] === '2026-07-06,150,8,non' && lines[2] === '2026-07-08,130,7,oui'; })(),
        s8Travel: typeof isAllowedTravelUrl === 'function' && typeof travelModes === 'function' && !!document.getElementById('calendarAgendaEstimate') && !!document.getElementById('travelStartForm') && !!document.getElementById('travelHome') && !!document.getElementById('travelMode'),
        goalsZones: typeof goalMatch === 'function' && typeof goalRank === 'function' && Array.isArray(TRAINING_GOALS) && document.querySelectorAll('#exerciseGoal option').length === 8,
        libNewOnly: !!document.getElementById('exerciseNewOnly') && (() => { const before = document.querySelectorAll('#exerciseCards .exercise-card').length; document.getElementById('exerciseNewOnly').click(); const on = document.querySelectorAll('#exerciseCards .exercise-card').length; document.getElementById('exerciseNewOnly').click(); const off = document.querySelectorAll('#exerciseCards .exercise-card').length; return before === 47 && on === 47 && off === 47; })(),
        equipmentFilter: typeof equipmentOptions === 'function' && !!document.getElementById('exerciseEquipment') && (() => { const sel = document.getElementById('exerciseEquipment'), opts = equipmentOptions(exercises); if (!opts.length || sel.options.length !== opts.length + 1) return false; const top = opts[0]; sel.value = top.kind; sel.dispatchEvent(new Event('change')); const shown = document.querySelectorAll('#exerciseCards .exercise-card').length; sel.value = 'all'; sel.dispatchEvent(new Event('change')); const all = document.querySelectorAll('#exerciseCards .exercise-card').length; return shown === top.count && all === 47; })(),
        favorites: typeof toggleFavorite === 'function' && !!document.getElementById('exerciseFavOnly') && !!document.getElementById('toggleFavExercise') && (() => { const before = (state.exerciseFavorites || []).slice(); state.exerciseFavorites = toggleFavorite([], 'Gainage planche'); renderExerciseLibrary(); const badge = document.querySelectorAll('#exerciseCards .ex-fav-badge').length; document.getElementById('exerciseFavOnly').click(); const favShown = document.querySelectorAll('#exerciseCards .exercise-card').length; document.getElementById('exerciseFavOnly').click(); state.exerciseFavorites = before; renderExerciseLibrary(); return badge >= 1 && favShown === 1; })(),
        zoneCoverage: typeof weeklyZoneCoverage === 'function' && !!document.getElementById('weeklyReviewZones') && weeklyZoneCoverage([{ date: '2026-07-08', exercise: 'Gainage planche' }], '2026-07-10').abs === 1,
        weeklySets: typeof weeklySetsPerZone === 'function' && typeof setLandmark === 'function' && !!document.getElementById('weeklySets') && weeklySetsPerZone([{ date: '2026-07-08', exercise: 'Gainage planche', sets: 3 }], '2026-07-10').abs === 3 && setLandmark(5).zone === 'low' && setLandmark(15).zone === 'ok' && setLandmark(25).zone === 'high',
        muscleBalance: typeof muscleBalance === 'function' && !!document.getElementById('muscleBalance') && (() => { const mb = muscleBalance([{ date: '2026-07-08', exercises: [{ name: 'Pompes classiques', sets: 4 }, { name: 'Tractions', sets: 3 }] }], '2026-07-10', 28); return mb && mb.push === 4 && mb.pull === 3 && mb.zone === 'balanced' && muscleBalance([], '2026-07-10') === null; })(),
        zoneFreshness: typeof zoneFreshness === 'function' && !!document.getElementById('zoneFreshness') && (() => { const zf = zoneFreshness([{ date: '2026-07-06', exercises: [{ name: 'Goblet squat kettlebell' }] }], '2026-07-10'); const by = Object.fromEntries(zf.map(z => [z.zone, z])); return zf.length === 7 && by.legs.days === 4 && by.legs.status === 'ready' && by.chest.status === 'never'; })(),
        focusSuggestion: typeof suggestTrainingFocus === 'function' && !!document.getElementById('trainingFocusSuggestion') && (() => { const tf = suggestTrainingFocus([{ date: '2026-07-10', exercises: [{ name: 'Goblet squat kettlebell', sets: 3 }] }, { date: '2026-07-04', exercises: [{ name: 'Tractions', sets: 3 }] }], '2026-07-10'); const zones = tf.map(z => z.zone); return tf.length === 5 && !zones.includes('legs') && tf[0].zone === 'abs' && suggestTrainingFocus([], 'x').length === 0; })(),
        neglectedZone: typeof neglectedZone === 'function' && neglectedZone({ legs: 2, back: 1, arms: 1 }, ['abs', 'legs', 'arms']) === 'abs' && neglectedZone({ abs: 1, legs: 1, arms: 1 }, ['abs', 'legs', 'arms']) === null,
        animEngine: typeof buildAnimatedArt === 'function' && typeof EXERCISE_ANIM === 'object' && /sheet-9 art-p1 frame-a/.test(buildAnimatedArt('9 p1 p4', '', 'x')) && /sheet-9 art-p4 frame-b/.test(buildAnimatedArt('9 p1 p4', '', 'x')) && /exercise-art-anim/.test(exercisePicture('Tractions', '', true)),
        zonePlan: typeof buildZonePlan === 'function' && typeof zoneTopExercises === 'function' && !!document.getElementById('zonePlanBtn') && !!document.getElementById('zonePlanDialog') && !!document.getElementById('zonePlanTable'),
        quickSession: typeof quickSessionPlan === 'function' && !!document.getElementById('quickSessionBtn') && !!document.getElementById('quickSessionResult') && (() => { const p = quickSessionPlan(exercises, { minutes: 20, zone: 'abs', maxExercises: 8 }); return p.count >= 1 && p.count <= 8 && p.totalMinutes > 0 && p.exercises.every(x => exerciseZones(x.name).includes('abs')) && quickSessionPlan(exercises, { zone: 'zzz' }).count === 0; })(),
        bodyGoals: typeof bodyGoalWorkout === 'function' && Array.isArray(BODY_GOALS) && BODY_GOALS.length === 7 && document.querySelectorAll('#bodyGoalsBar [data-bodygoal]').length === 7 && (() => { const w = bodyGoalWorkout('abs', exercises, { count: 5 }); const fb = bodyGoalWorkout('fullbody', exercises, { count: 5 }); return w && w.title === 'Abdos béton' && w.exercises.length >= 2 && w.exercises.every(e => exerciseZones(e.name).includes('abs') && e.sets > 0) && bodyGoalWorkout('legs', exercises).exercises.every(e => exerciseZones(e.name).some(z => z === 'legs' || z === 'glutes')) && fb.exercises.length === 5; })(),
        weekProgram: typeof buildTrainingWeek === 'function' && !!document.getElementById('wpGoals') && document.querySelectorAll('#wpGoals input').length === 7 && !!document.getElementById('wpGenerate') && !!document.getElementById('wpSchedule') && !!document.getElementById('wpSameDay'),
        objectiveProgram: typeof objectiveProgram === 'function' && Array.isArray(FITNESS_OBJECTIVES) && FITNESS_OBJECTIVES.length === 5 && !!document.getElementById('objectiveGenerate') && !!document.getElementById('objectiveSelect') && (() => { const p = objectiveProgram('athletique', exercises, { perSession: 5 }); const m = p.week.filter(s => s.kind === 'muscu'); const c = p.week.filter(s => s.kind === 'course'); return p.strength === 3 && p.runs === 3 && p.week.length === 6 && m.length === 3 && c.length === 3 && m.every(s => s.exercises.length >= 3 && s.exercises.every(e => e.sets > 0)) && objectiveProgram('zzz', exercises) === null; })(),
        objectiveProgression: typeof blockPhase === 'function' && typeof progressSets === 'function' && blockPhase(0).phase === 'Base' && blockPhase(3).deload === true && progressSets(3, 1) === 4 && progressSets(3, 3) === 2,
        currentBlock: typeof currentBlock === 'function' && !!document.getElementById('blockStatus') && (() => { const b = currentBlock('2026-07-06', '2026-07-15'); return b && b.week === 2 && b.phase.phase === 'Volume' && b.deloadInWeeks === 2 && currentBlock('2026-07-06', '2026-08-10').done === true && currentBlock('', 'x') === null; })(),
        blockHeadsUp: typeof blockPhaseHeadsUp === 'function' && (() => { const s4 = blockPhaseHeadsUp(currentBlock('2026-07-06', '2026-07-27')); const s3 = blockPhaseHeadsUp(currentBlock('2026-07-06', '2026-07-20')); return s4 && s4.phase === 'deload' && s4.showNextAdvice === true && s3 && s3.phase === 'preload' && s3.showNextAdvice === false && blockPhaseHeadsUp(currentBlock('2026-07-06', '2026-07-06')) === null && blockPhaseHeadsUp(null) === null; })(),
        nextBlockAdvice: typeof nextBlockAdvice === 'function' && nextBlockAdvice({ adherence: 30 }).action === 'ease' && nextBlockAdvice({ adherence: 85, loadStatus: 'push' }).action === 'progress' && nextBlockAdvice({}).action === 'keep',
        blockForecast: typeof bestStrengthForecast === 'function' && (() => { const wo = (date, name, load, reps) => ({ date, exercises: [{ name, setLogs: [{ completed: true, load, reps }] }] }); const workouts = [wo('2026-06-08', 'Squat', 90, 1), wo('2026-06-15', 'Squat', 92.5, 1), wo('2026-06-22', 'Squat', 95, 1), wo('2026-06-29', 'Squat', 97.5, 1)]; const f = bestStrengthForecast(workouts, { step: 5, todayKey: '2026-06-29' }); return f && f.exercise === 'Squat' && f.milestone === 100 && f.weeks === 1 && bestStrengthForecast([], {}) === null; })(),
        blockNeglect: typeof neglectedZoneReport === 'function' && (() => { const w = [{ date: '2026-07-10', exercises: [{ name: 'Fentes arrière', completedSets: 4 }, { name: 'Pont fessier', completedSets: 4 }] }, { date: '2026-07-06', exercises: [{ name: 'Chaise au mur', completedSets: 4 }] }]; const r = neglectedZoneReport(w, '2026-07-13', 28); return r && r.sets === 0 && r.neglected === true && r.bySets.legs > 0 && neglectedZoneReport([], '2026-07-13') === null; })(),
        blockPushPull: typeof pushPullAdvice === 'function' && typeof muscleBalance === 'function' && (() => { const heavy = pushPullAdvice({ push: 8, pull: 3, ratio: 2.67, zone: 'push-heavy' }); const bal = pushPullAdvice({ push: 6, pull: 6, ratio: 1, zone: 'balanced' }); return heavy && heavy.ok === false && /tirage|dos/i.test(heavy.advice) && bal.ok === true && pushPullAdvice({ push: 2, pull: 1, zone: 'push-heavy' }) === null && pushPullAdvice(null) === null; })(),
        blockPlateau: typeof strengthPlateauAny === 'function' && (() => { const wo = (date, name, load, reps) => ({ date, exercises: [{ name, setLogs: [{ completed: true, load, reps }] }] }); const flat = [wo('2026-06-01', 'Squat', 100, 5), wo('2026-06-08', 'Squat', 98, 5), wo('2026-06-15', 'Squat', 99, 5), wo('2026-06-22', 'Squat', 97, 5)]; const up = [wo('2026-06-01', 'Squat', 90, 5), wo('2026-06-08', 'Squat', 95, 5), wo('2026-06-15', 'Squat', 100, 5), wo('2026-06-22', 'Squat', 105, 5)]; const r = strengthPlateauAny(flat, { window: 3 }); return r.plateau === true && r.exercise === 'Squat' && strengthPlateauAny(up, { window: 3 }).plateau === false && strengthPlateauAny([]).plateau === false && nextBlockAdvice({ adherence: 80, loadStatus: 'maintain', plateau: r.plateau }).action === 'vary'; })(),
        phaseSetsForDay: typeof phaseSetsForDay === 'function' && phaseSetsForDay(3, '2026-07-06', '2026-07-15') === 4 && phaseSetsForDay(3, '2026-07-06', '2026-07-29') === 2 && phaseSetsForDay(3, '', '2026-07-15') === 3,
        blockHistory: typeof archiveBlock === 'function' && typeof blockHistorySummary === 'function' && !!document.getElementById('blockHistory') && (() => { let h = archiveBlock([], { objective: 'seche', start: '2026-05-04', weeks: 4 }); h = archiveBlock(h, { objective: 'muscle', start: '2026-06-01', weeks: 4 }); const s = blockHistorySummary(h); return h.length === 2 && s.count === 2 && s.last.objective === 'muscle' && blockHistorySummary([]) === null; })(),
        blockCompare: typeof blockComparison === 'function' && typeof blockWindowStats === 'function' && !!document.getElementById('blockCompare') && (() => { const wo = (date, load, reps) => ({ date, exercises: [{ name: 'Squat', setLogs: [{ completed: true, load, reps }] }] }); const workouts = [wo('2026-05-06', 20, 10), wo('2026-05-20', 20, 10), wo('2026-06-03', 30, 10), wo('2026-06-10', 30, 10), wo('2026-06-20', 30, 10)]; const hist = [{ objective: 'seche', start: '2026-05-04', end: '2026-05-31', weeks: 4 }, { objective: 'muscle', start: '2026-06-01', end: '2026-06-28', weeks: 4 }]; const c = blockComparison(hist, workouts); return c && c.blocks === 2 && c.first.tonnage === 400 && c.last.tonnage === 900 && c.tonnagePct === 125 && c.trend === 'up' && blockComparison(hist.slice(0, 1), workouts) === null && blockWindowStats(workouts, '2026-05-01', '2026-05-31').sessions === 2; })(),
        blockShare: typeof shareableBlockProgress === 'function' && typeof blockProgressText === 'function' && (() => { const wo = (date, name, load, reps) => ({ date, exercises: [{ name, setLogs: [{ completed: true, load, reps }] }] }); const workouts = [wo('2026-05-06', 'Squat', 60, 5), wo('2026-06-03', 'Squat', 75, 5)]; const hist = [{ objective: 'seche', start: '2026-05-04', end: '2026-05-31', weeks: 4 }, { objective: 'muscle', start: '2026-06-01', end: '2026-06-28', weeks: 4 }]; const s = shareableBlockProgress(hist, workouts); return s && /progression/i.test(s.title) && /2 blocs/i.test(s.text) && shareableBlockProgress(hist.slice(0, 1), workouts) === null; })(),
        blockExProgress: typeof blockExerciseProgress === 'function' && typeof bestE1rmByExercise === 'function' && (() => { const wo = (date, name, load, reps) => ({ date, exercises: [{ name, setLogs: [{ completed: true, load, reps }] }] }); const workouts = [wo('2026-05-06', 'Squat', 60, 5), wo('2026-06-03', 'Squat', 75, 5)]; const hist = [{ objective: 'muscle', start: '2026-05-04', end: '2026-05-31', weeks: 4 }, { objective: 'muscle', start: '2026-06-01', end: '2026-06-28', weeks: 4 }]; const p = blockExerciseProgress(hist, workouts); return p.length === 1 && p[0].name === 'Squat' && p[0].firstE1rm === 70 && p[0].lastE1rm === 87.5 && p[0].deltaPct === 25 && blockExerciseProgress(hist.slice(0, 1), workouts).length === 0; })(),
        objectiveMemory: !!document.getElementById('objectiveSelect') && 'fitnessObjective' in state && 'objectiveSeed' in state && (() => { const p0 = objectiveProgram('muscle', exercises, { perSession: 5, seed: 0 }); const p1 = objectiveProgram('muscle', exercises, { perSession: 5, seed: 1 }); const names = pr => pr.week.filter(s => s.kind === 'muscu').map(s => s.exercises.map(e => e.name).join(',')).join('|'); return names(p0) !== names(p1); })(),
        objectiveRuns: (() => { const t = pr => pr.week.filter(s => s.kind === 'course').map(s => s.type); const s = objectiveProgram('seche', exercises); const m = objectiveProgram('muscle', exercises); return s.runFocus === 'tempo & fractionné' && (t(s).includes('fractionne') || t(s).includes('tempo')) && t(m).every(x => x === 'facile'); })(),
        objectiveSummary: typeof programWeekSummary === 'function' && (() => { const p = objectiveProgram('athletique', exercises); const s = programWeekSummary(p.week); return s.sessions === p.week.length && s.muscu === 3 && s.course === 3 && s.minutes > 0 && s.hours > 0; })(),
        objectiveCopy: typeof objectiveProgramText === 'function' && (() => { const p = objectiveProgram('athletique', exercises); const txt = objectiveProgramText(p); return txt.includes('Corps athlétique') && txt.includes('🏋️') && objectiveProgramText(null) === ''; })(),
        objectiveShare: typeof shareableProgram === 'function' && (() => { const p = objectiveProgram('athletique', exercises); const s = shareableProgram(p); return s && /Corps athlétique/.test(s.title) && /ma semaine/i.test(s.title) && s.text === objectiveProgramText(p) && shareableProgram(null) === null; })(),
        a11yObjective: (() => { const sel = document.getElementById('objectiveSelect'), res = document.getElementById('objectiveResult'), rp = document.getElementById('runPlanResult'); return !!sel && (sel.getAttribute('aria-label') || '').length > 3 && !!res && res.getAttribute('aria-live') === 'polite' && !!rp && rp.getAttribute('aria-live') === 'polite'; })(),
        selectStyled: (() => { const s = document.getElementById('objectiveSelect'); if (!s) return false; const cs = getComputedStyle(s); return (cs.appearance === 'none' || cs.webkitAppearance === 'none') && cs.backgroundImage.indexOf('svg') !== -1; })(),
        scrollbarStyled: (() => { const thin = getComputedStyle(document.body).scrollbarWidth === 'thin'; let rule = false; try { for (const ss of document.styleSheets) { let rules; try { rules = ss.cssRules; } catch (e) { continue; } for (const r of rules) { if (r.selectorText && r.selectorText.indexOf('-webkit-scrollbar') !== -1) { rule = true; } } } } catch (e) {} return thin || rule; })(),
        inputPolish: (() => { const cb = document.getElementById('wpSameDay'); const ok = cb ? getComputedStyle(cb).accentColor !== 'auto' : false; let rule = false; try { for (const ss of document.styleSheets) { let rules; try { rules = ss.cssRules; } catch (e) { continue; } for (const r of rules) { if (r.selectorText && r.selectorText.indexOf('focus-visible') !== -1) { rule = true; } } } } catch (e) {} return ok || rule; })(),
        streakMilestone: typeof nextStreakMilestone === 'function' && !!document.getElementById('streakHint') && nextStreakMilestone(5).milestone === 7 && nextStreakMilestone(5).remaining === 2 && nextStreakMilestone(365) === null,
        wellness: typeof wellnessRoutine === 'function' && Array.isArray(WELLNESS_ROUTINES) && WELLNESS_ROUTINES.length >= 5 && !!document.getElementById('wellnessBar') && document.querySelectorAll('#wellnessBar [data-wellness]').length >= 5 && (() => { const r = wellnessRoutine('cooldown'); return r && r.exercises.length >= 3 && r.exercises.every(e => e.unit === 'sec') && wellnessRoutine('zzz') === null && document.querySelectorAll('#wellnessBar [data-wellness-sched]').length >= 5 && typeof wellnessRecurringEvent === 'function' && wellnessRecurringEvent('cooldown').refId === 'wellness-cooldown' && wellnessRecurringEvent('cooldown').kind === 'sport'; })(),
        wellnessSuggest: typeof suggestedRoutine === 'function' && !!document.getElementById('wellnessSuggest') && suggestedRoutine('deload', 40).key === 'cooldown' && suggestedRoutine('push', 85).key === 'warmup' && !!wellnessRoutine(suggestedRoutine('maintain', 60).key),
        wellnessRoutineShare: typeof shareableRoutine === 'function' && (() => { const s = shareableRoutine('warmup'); return s && /routine bien-être/i.test(s.title) && /1\. /.test(s.text) && shareableRoutine('zzz') === null; })(),
        wellnessContext: typeof contextualWellnessRoutine === 'function' && typeof workoutDominantZone === 'function' && (() => { const legs = { workouts: [{ date: '2026-07-13', type: 'strength', exercises: [{ name: 'Split squat bulgare' }, { name: 'Fentes arrière' }] }] }; const run = { workouts: [{ date: '2026-07-13', type: 'run' }] }; return contextualWellnessRoutine(legs, '2026-07-13', 'maintain', 60).key === 'hips' && contextualWellnessRoutine(run, '2026-07-13', 'maintain', 60).key === 'ankles' && contextualWellnessRoutine({ workouts: [] }, '2026-07-13', 'maintain', 40).key === 'cooldown' && workoutDominantZone(legs.workouts[0]) === 'legs'; })(),
        wellnessStreak: typeof wellnessStreak === 'function' && typeof logWellnessDone === 'function' && typeof wellnessCountInWindow === 'function' && !!document.getElementById('wellnessStreak') && 'wellnessDone' in state && (() => { let l = logWellnessDone([], 'hips', '2026-07-12'); l = logWellnessDone(l, 'warmup', '2026-07-13'); return l.length === 2 && wellnessStreak(l, '2026-07-13') === 2 && wellnessCountInWindow(l, '2026-07-06', '2026-07-13') === 2; })(),
        wellnessMinutes: typeof wellnessMinutesForKey === 'function' && typeof wellnessMinutesInWindow === 'function' && (() => { const log = [{ date: '2026-07-13', key: 'hips' }, { date: '2026-07-13', key: 'warmup' }, { date: '2026-07-05', key: 'stretch' }]; return wellnessMinutesForKey('hips') === 6 && wellnessMinutesForKey('parcours-reveil') === wellnessParcours('reveil').minutes && wellnessMinutesForKey('zzz') === 0 && wellnessMinutesInWindow(log, '2026-07-06', '2026-07-13') === 11 && wellnessMinutesInWindow([], '2026-07-06', '2026-07-13') === 0; })(),
        wellnessZone: typeof neglectedMobilityZone === 'function' && Array.isArray(WELLNESS_ZONE_ROUTINES) && !!document.getElementById('wellnessZone') && (() => { const n0 = neglectedMobilityZone([], '2026-07-13', 7); const mixed = [{ date: '2026-07-11', key: 'hips' }, { date: '2026-07-10', key: 'shoulders' }, { date: '2026-07-09', key: 'backpain' }, { date: '2026-06-20', key: 'ankles' }, { date: '2026-07-08', key: 'neck' }, { date: '2026-07-07', key: 'wrists' }]; const nm = neglectedMobilityZone(mixed, '2026-07-13', 7); return n0.key === 'hips' && n0.lastDays === null && !!n0.emoji && nm.key === 'ankles' && nm.lastDays === 23; })(),
        wellnessFamilies: typeof wellnessFamilyBreakdown === 'function' && !!document.getElementById('wellnessFamilies') && (() => { const log = [{ date: '2026-07-13', key: 'hips' }, { date: '2026-07-12', key: 'neck' }, { date: '2026-07-11', key: 'stretch' }, { date: '2026-07-13', key: 'zzz' }]; const b = wellnessFamilyBreakdown(log, '2026-07-06', '2026-07-13'); return b[0].family === 'Mobilité' && b[0].count === 2 && !!b[0].emoji && b.reduce((s, x) => s + x.count, 0) === 3 && wellnessFamilyBreakdown([], '2026-07-06', '2026-07-13').length === 0; })(),
        shareableWellness: typeof shareableWellness === 'function' && !!document.getElementById('wellnessShareBtn') && (() => { const log = [{ date: '2026-07-11', key: 'hips' }, { date: '2026-07-12', key: 'neck' }, { date: '2026-07-13', key: 'warmup' }]; const s = shareableWellness(log, '2026-07-13'); return s && /bilan bien-être/i.test(s.title) && /3 routines au total/.test(s.text) && /min de mobilité/.test(s.text) && shareableWellness([], '2026-07-13') === null; })(),
        bestWellnessWeek: typeof bestWellnessWeek === 'function' && (() => { const log = [{ date: '2026-07-06', key: 'hips' }, { date: '2026-07-07', key: 'neck' }, { date: '2026-07-08', key: 'warmup' }, { date: '2026-07-13', key: 'morning' }]; const b = bestWellnessWeek(log, '2026-07-13'); return b.weekStart === '2026-07-06' && b.count === 3 && b.isCurrent === false && bestWellnessWeek([], '2026-07-13') === null; })(),
        wellnessBestStreak: typeof wellnessBestStreak === 'function' && (() => { const log = [{ date: '2026-06-01', key: 'a' }, { date: '2026-06-02', key: 'b' }, { date: '2026-06-03', key: 'c' }, { date: '2026-06-04', key: 'd' }, { date: '2026-07-13', key: 'e' }]; return wellnessBestStreak(log) === 4 && wellnessBestStreak([{ date: '2026-07-13', key: 'a' }, { date: '2026-07-13', key: 'b' }]) === 1 && wellnessBestStreak([]) === 0; })(),
        wellnessGoal: typeof wellnessGoalProgress === 'function' && !!document.getElementById('wellnessGoal') && 'wellnessWeeklyGoal' in state && (() => { const g = wellnessGoalProgress(2, 3); return g.done === 2 && g.pct === 67 && g.reached === false && wellnessGoalProgress(4, 3).reached === true && wellnessGoalProgress(0, 99).target === 14; })(),
        wellnessNudge: typeof wellnessInactivity === 'function' && !!document.getElementById('wellnessNudge') && (() => { const r = wellnessInactivity([{ date: '2026-07-08', key: 'a' }], '2026-07-13', 3); return r.inactive === true && r.days === 5 && wellnessInactivity([{ date: '2026-07-12', key: 'a' }], '2026-07-13', 3).inactive === false && wellnessInactivity([], '2026-07-13').days === null; })(),
        wellnessBadges: typeof wellnessBadges === 'function' && typeof newWellnessBadge === 'function' && (() => { const three = [{ date: '2026-07-11', key: 'a' }, { date: '2026-07-12', key: 'b' }, { date: '2026-07-13', key: 'c' }]; const b = wellnessBadges(three, '2026-07-13'); const b0 = wellnessBadges([], '2026-07-13'); return b.streakBadge.days === 3 && b.totalBadge === null && b.nextStreak.days === 7 && newWellnessBadge(b0, b).kind === 'streak' && newWellnessBadge(b, b) === null; })(),
        wellnessHeatmap: typeof wellnessWeekHeatmap === 'function' && !!document.getElementById('wellnessHeatmap') && (() => { const h = wellnessWeekHeatmap([{ date: '2026-07-13', key: 'a' }, { date: '2026-07-13', key: 'b' }, { date: '2026-07-11', key: 'c' }], '2026-07-13', 7); return h.length === 7 && h[6].count === 2 && h[6].date === '2026-07-13' && h.find(c => c.date === '2026-07-11').count === 1 && wellnessWeekHeatmap([], 'x', 7).length === 0; })(),
        wellnessParcours: typeof wellnessParcours === 'function' && !!document.getElementById('wellnessParcours') && document.querySelectorAll('#wellnessParcours [data-parcours]').length >= 3 && (() => { const p = wellnessParcours('reveil'); return p && p.count === 2 && p.exercises.length >= 6 && p.minutes > 0 && wellnessParcours('zzz') === null; })(),
        shareApp: typeof shareAppPayload === 'function' && !!document.getElementById('shareAppBtn') && (() => { const p = shareAppPayload('https://adrienlvl.github.io/irl-lvp-up/'); return p.title && /RPG de vie|IRL LVP UP/.test(p.text) && p.url === 'https://adrienlvl.github.io/irl-lvp-up/' && !('url' in shareAppPayload('file:///x')) && !('url' in shareAppPayload('')); })(),
        membership: typeof membershipInfo === 'function' && Array.isArray(MEMBERSHIP_TIERS) && !!document.getElementById('membershipLine') && (() => { const d0 = membershipInfo('2026-07-13', '2026-07-13'); const d10 = membershipInfo('2026-07-03', '2026-07-13'); return d0.days === 0 && d0.tier.label === 'Nouveau' && d0.next.days === 7 && d10.days === 10 && d10.tier.label === 'Lancé' && d10.next.remaining === 20 && membershipInfo('x', 'y') === null; })(),
        launchTarget: typeof launchTarget === 'function' && Array.isArray(LAUNCH_TARGETS) && LAUNCH_TARGETS.includes('wellness') && LAUNCH_TARGETS.includes('today') && launchTarget('?go=wellness') === 'wellness' && launchTarget('?go=today') === 'today' && launchTarget('?go=coach') === 'coach' && launchTarget('?go=hack') === null && launchTarget('') === null && !!document.querySelector('.wellness-panel') && !!document.querySelector('.my-day-panel'),
        whatsNew: typeof whatsNewSince === 'function' && typeof compareVersions === 'function' && typeof CHANGELOG !== 'undefined' && !!document.getElementById('whatsNewCard') && (() => { const log = [{ v: '1.9.190', emoji: '✨', text: 'C' }, { v: '1.9.189', emoji: '📈', text: 'B' }, { v: '1.9.188', emoji: '🧘', text: 'A' }]; const seen = whatsNewSince('1.9.188', log); return compareVersions('1.10.0', '1.9.99') === 1 && whatsNewSince('', log).length === 0 && seen.length === 2 && seen[0].v === '1.9.190' && whatsNewSince('1.9.190', log).length === 0 && Array.isArray(CHANGELOG) && CHANGELOG[0].v === '1.9.233'; })(),
        tonnageTrend: typeof weeklyTonnageTrend === 'function' && !!document.getElementById('tonnageTrend') && (() => { const w = [{ date: '2026-07-06', exercises: [{ name: 'Squat', load: 100, reps: 5, sets: 4 }] }, { date: '2026-07-13', exercises: [{ name: 'Squat', load: 100, reps: 5, sets: 6 }] }]; const t = weeklyTonnageTrend(w, '2026-07-13', 8); return t && t.weeks.length === 8 && t.weeks[7].tonnage === 3000 && t.last === 3000 && t.max === 3000 && t.trend === 'up' && weeklyTonnageTrend([], '2026-07-13', 8) === null; })(),
        blocksByObjective: typeof blocksByObjective === 'function' && !!document.getElementById('blocksByObjective') && (() => { const wo = (date, load, reps) => ({ date, exercises: [{ name: 'Squat', setLogs: [{ completed: true, load, reps }] }] }); const workouts = [wo('2026-05-06', 20, 10), wo('2026-06-03', 30, 10), wo('2026-06-10', 30, 10)]; const history = [{ objective: 'seche', start: '2026-05-04', end: '2026-05-31', weeks: 4 }, { objective: 'muscle', start: '2026-06-01', end: '2026-06-28', weeks: 4 }]; const r = blocksByObjective(history, workouts); return r.length === 2 && r[0].objective === 'muscle' && r[0].blocks === 1 && r[0].sessions === 2 && blocksByObjective([], workouts).length === 0; })(),
        bestSession: typeof bestSessionTonnage === 'function' && (() => { const w = [{ date: '2026-06-20', exercises: [{ name: 'Squat', load: 100, reps: 5, sets: 8 }] }, { date: '2026-07-01', exercises: [{ name: 'Squat', load: 100, reps: 5, sets: 6 }] }]; const b = bestSessionTonnage(w); return b.tonnage === 4000 && b.date === '2026-06-20' && b.count === 2 && b.isLatest === false && bestSessionTonnage([]) === null; })(),
        bestTonnageWeek: typeof bestTonnageWeek === 'function' && (() => { const w = [{ date: '2026-07-06', exercises: [{ name: 'Squat', load: 100, reps: 5, sets: 5 }] }, { date: '2026-07-08', exercises: [{ name: 'Squat', load: 100, reps: 5, sets: 5 }] }, { date: '2026-07-13', exercises: [{ name: 'Squat', load: 100, reps: 5, sets: 6 }] }]; const b = bestTonnageWeek(w, '2026-07-13'); return b.weekStart === '2026-07-06' && b.tonnage === 5000 && b.sessions === 2 && b.isCurrent === false && bestTonnageWeek([], '2026-07-13') === null; })(),
        runWeekGoal: typeof runWeekGoal === 'function' && !!document.getElementById('runWeekGoal') && (() => { const w = [{ type: 'run', date: '2026-07-13', distance: 8 }, { type: 'run', date: '2026-07-06', distance: 15 }]; const g = runWeekGoal(w, '2026-07-13', 20); return g.km === 8 && g.pct === 40 && g.remaining === 12 && g.reached === false && runWeekGoal([{ type: 'run', date: '2026-07-13', distance: 25 }], '2026-07-13', 20).reached === true && runWeekGoal(w, '2026-07-13', 0) === null; })(),
        weekBalance: typeof weekTrainingBalance === 'function' && !!document.getElementById('weekBalance') && (() => { const w = [{ date: '2026-07-13', exercises: [{ name: 'Squat', load: 100, reps: 5, sets: 5 }] }, { date: '2026-07-12', type: 'strength', exercises: [{ name: 'Dev', load: 60, reps: 8, sets: 4 }] }, { date: '2026-07-13', type: 'run' }, { date: '2026-07-10', type: 'run' }]; const b = weekTrainingBalance(w, '2026-07-13', 7); return b.strength === 2 && b.runs === 2 && b.total === 4 && b.label === 'Bon équilibre' && weekTrainingBalance([], '2026-07-13', 7) === null; })(),
        trainingByWeekday: typeof trainingByWeekday === 'function' && !!document.getElementById('trainingByWeekday') && (() => { const w = [{ date: '2026-07-13' }, { date: '2026-07-07' }, { date: '2026-06-30' }, { date: '2026-07-08' }]; const r = trainingByWeekday(w, '2026-07-13', 56); return r.bestDay === 1 && r.bestCount === 2 && r.total === 4 && JSON.stringify(r.counts) === JSON.stringify([1, 2, 1, 0, 0, 0, 0]) && trainingByWeekday([], '2026-07-13', 56).bestDay === null; })(),
        trainingConsistency: typeof trainingConsistency === 'function' && !!document.getElementById('trainingConsistency') && (() => { const reg = [{ date: '2026-07-01' }, { date: '2026-07-04' }, { date: '2026-07-07' }, { date: '2026-07-10' }, { date: '2026-07-13' }]; const c = trainingConsistency(reg, '2026-07-13', 28); return c.sessions === 5 && c.avgGapDays === 3 && c.regularity === 100 && c.label === 'Très régulier' && trainingConsistency([{ date: '2026-07-13' }], '2026-07-13') === null; })(),
        wellnessExpress: typeof expressRoutine === 'function' && !!document.getElementById('wellnessExpress') && document.querySelectorAll('#wellnessExpress [data-wx]').length >= 3 && (() => { const keys4 = routinesByTimeBudget(4).map(r => r.key); const ok = [0, 1, 2, 3, 4].every(s => keys4.includes(expressRoutine(4, null, s))); return ok && expressRoutine(6, null, 7) === expressRoutine(6, null, 7) && expressRoutine(1, null, 3) === null && !!wellnessRoutine(expressRoutine(8, null, 5)).exercises.length; })(),
        wellnessTimeFilter: typeof routinesByTimeBudget === 'function' && !!document.getElementById('wellnessTimeFilter') && document.querySelectorAll('#wellnessTimeFilter [data-wtf]').length >= 4 && document.querySelectorAll('#wellnessBar [data-wellness]').length === WELLNESS_ROUTINES.length && (() => { const all = routinesByTimeBudget(0), q = routinesByTimeBudget(4); return all.length === WELLNESS_ROUTINES.length && q.length > 0 && q.length < all.length && q.every(r => r.minutes <= 4) && q[0].minutes >= q[q.length - 1].minutes && !routinesByTimeBudget(6).some(r => r.key === 'stretch') && routinesByTimeBudget(8).some(r => r.key === 'stretch'); })(),
        wellnessSurprise: typeof surpriseRoutine === 'function' && !!document.getElementById('wellnessSurprise') && WELLNESS_ROUTINES.length >= 11 && !!wellnessRoutine('ankles') && !!wellnessRoutine('neck') && !!wellnessRoutine('wrists') && WELLNESS_ROUTINES.map(r => r.key).includes(surpriseRoutine(null, 5)) && surpriseRoutine('warmup', 3) !== 'warmup' && surpriseRoutine(null, 7) === surpriseRoutine(null, 7),
        replayOnboarding: !!document.getElementById('settingsReplayOnboarding'),
        onboardingSetup: typeof onboardingSetup === 'function' && !!document.getElementById('onboardingObjective') && !!document.getElementById('onbWeight') && !!document.getElementById('onbSex') && !!document.getElementById('onbTargetWeight') && !!document.getElementById('onbDistance') && !!document.getElementById('onbActivity') && !!document.getElementById('onbName') && !!document.getElementById('playerName') && (() => { const s = onboardingSetup({ name: '  Adrien  ', weight: 80, height: 178, age: 30, sex: 'homme', objective: 'muscle', sessions: 4, targetWeight: 75, distance: 25, activity: 'actif', equipment: { kettlebell: true } }); return s.fitnessObjective === 'muscle' && s.profile.weight === 80 && s.goals.sessions === 4 && s.goals.targetWeight === 75 && s.goals.distance === 25 && s.profile.activityLevel === 'actif' && s.profile.name === 'Adrien' && onboardingSetup({ name: 42 }).profile.name === '' && s.profile.equipment.kettlebell === true && !!document.getElementById('onbLimitations') && !!document.getElementById('limitationsNote') && onboardingSetup({ limitations: '  genou  ' }).profile.limitations === 'genou' && onboardingSetup({ limitations: 7 }).profile.limitations === ''; })(),
        onboardingDays: typeof assignProgramDays === 'function' && document.querySelectorAll('#onbDays input[type=checkbox]').length === 7 && (() => { const s = onboardingSetup({ objective: 'seche', days: [5, 2, 2] }); if (JSON.stringify(s.profile.availableDays) !== '[2,5]') return false; const w = [{ kind: 'muscu', weekday: 1 }, { kind: 'course', weekday: 3 }, { kind: 'muscu', weekday: 5 }]; const r = assignProgramDays(w, [2, 5]); return r.length === 3 && r.every(x => x.weekday === 2 || x.weekday === 5) && JSON.stringify(assignProgramDays(w, []).map(x => x.weekday)) === '[1,3,5]'; })(),
        onboardingMeter: typeof onboardingCompleteness === 'function' && !!document.getElementById('onboardingMeter') && (() => { const f = onboardingCompleteness({ objective: 'muscle', weight: 80, height: 178, age: 30, days: [1, 3], slot: 'soir' }); const m = onboardingCompleteness({ objective: 'muscle' }); return f.percent === 100 && f.nutritionReady === true && m.nutritionReady === false && m.missing.includes('poids'); })(),
        onboardingCalories: typeof onboardingNutritionEstimate === 'function' && !!document.getElementById('onboardingCalories') && (() => { const e = onboardingNutritionEstimate({ objective: 'seche', weight: 80, height: 178, age: 30, sex: 'homme', sessions: 4 }); return e && e.maintenance > 0 && e.target > 0 && e.target < e.maintenance && e.dir === 'déficit' && onboardingNutritionEstimate({ objective: 'seche', weight: 80 }) === null; })(),
        starterHabit: typeof starterHabitFor === 'function' && !!document.getElementById('onbStarterHabit') && !!document.getElementById('onbStarterHabitLabel') && (() => { const h = starterHabitFor('seche'); return /eau/i.test(h.name) && h.weekdays.length === 7 && starterHabitFor('zzz').name === STARTER_HABITS.athletique.name && normalizeHabit(starterHabitFor('muscle')).weekdays.length === 7; })(),
        onboardingSuggest: typeof suggestObjective === 'function' && !!document.getElementById('onboardingSuggest') && (() => { const cut = suggestObjective({ weight: 90, height: 178, targetWeight: 80 }); return cut.key === 'seche' && suggestObjective({ weight: 65, height: 180, targetWeight: 72 }).key === 'muscle' && suggestObjective({ weight: 72, height: 178 }).key === 'athletique' && suggestObjective({ weight: 52, height: 180 }).key === 'muscle' && suggestObjective({ weight: 80 }) === null; })(),
        onboardingDraft: typeof sanitizeOnboardingDraft === 'function' && !!document.getElementById('onbDraftNote') && !!document.getElementById('onbDraftClear') && (() => { const d = sanitizeOnboardingDraft({ objective: 'seche', weight: '80', slot: 'matin', days: [1, 1, 9] }); return d && d.objective === 'seche' && d.weight === 80 && d.slot === 'matin' && JSON.stringify(d.days) === '[1]' && sanitizeOnboardingDraft({}) === null && sanitizeOnboardingDraft({ objective: 'zzz' }) === null; })(),
        onboardingRecap: typeof onboardingFirstSession === 'function' && !!document.getElementById('onboardingRecapDialog') && !!document.getElementById('onboardingRecapBody') && (() => { const week = [{ kind: 'course', title: 'Run', weekday: 5 }, { kind: 'muscu', title: 'Jambes', weekday: 1, exercises: [{ name: 'Squat', sets: 3, reps: 10 }] }]; const f = onboardingFirstSession(week, '2026-07-13'); return f.title === 'Jambes' && f.date === '2026-07-13' && f.dayLabel === 'Lundi' && f.guidable === true && onboardingFirstSession([], '2026-07-13') === null; })(),
        onboardingSlot: typeof sessionTimesForSlot === 'function' && !!document.getElementById('onbSlot') && (() => { const t = sessionTimesForSlot('matin'); const d = sessionTimesForSlot(''); return t.muscu === '07:00' && t.course === '07:30' && d.muscu === '18:00' && d.course === '07:30' && onboardingSetup({ slot: 'soir' }).profile.trainingSlot === 'soir' && onboardingSetup({ slot: 'x' }).profile.trainingSlot === ''; })(),
        onboardingLevel: typeof perSessionForLevel === 'function' && !!document.getElementById('onbLevel') && perSessionForLevel('debutant') === 4 && perSessionForLevel('avance') === 6 && perSessionForLevel('x') === 5 && onboardingSetup({ level: 'avance' }).profile.level === 'avance' && onboardingSetup({ level: 'zzz' }).profile.level === 'debutant',
        starterChecklist: typeof starterChecklist === 'function' && !!document.getElementById('starterCard') && (() => { const s = starterChecklist({ fitnessObjective: 'seche', blockStart: '2026-07-13', weights: [{ value: 80 }], workouts: [{}], nutrition: [{ date: '2026-07-13', water: 5 }], quests: [{ done: true }] }, '2026-07-13'); return s.total === 6 && s.done === 6 && s.complete === true && starterChecklist({}).done === 0; })(),
        objectiveWelcome: typeof objectiveWelcome === 'function' && !!document.getElementById('onboardingWelcome') && objectiveWelcome('muscle') !== objectiveWelcome('seche') && objectiveWelcome('zzz') === objectiveWelcome('athletique') && objectiveWelcome('endurance').length > 20,
        wakeLock: typeof shouldReacquireWakeLock === 'function' && shouldReacquireWakeLock(true, 'visible') === true && shouldReacquireWakeLock(true, 'hidden') === false && shouldReacquireWakeLock(false, 'visible') === false && typeof requestGuidedWakeLock === 'function' && typeof releaseGuidedWakeLock === 'function',
        appBadge: typeof pendingBadgeCount === 'function' && typeof updateAppBadge === 'function' && pendingBadgeCount({ quests: [{ done: false }, { done: true }], agenda: [{ date: '2026-07-13', kind: 'sport' }] }, '2026-07-13') === 2 && pendingBadgeCount({}, '2026-07-13') === 0,
        haptics: typeof vibrationPattern === 'function' && typeof haptic === 'function' && Array.isArray(vibrationPattern('restEnd')) && vibrationPattern('setDone')[0] === 40 && vibrationPattern('zzz') === null && vibrationPattern('record').length >= 3 && Array.isArray(vibrationPattern('badge')) && Array.isArray(vibrationPattern('questDone')),
        safeArea: (() => { const vp = document.querySelector('meta[name=viewport]'); const hasFit = !!vp && /viewport-fit=cover/.test(vp.content); let hasEnv = false; try { for (const ss of document.styleSheets) { let rules; try { rules = ss.cssRules; } catch (e) { continue; } if (!rules) continue; for (const r of rules) { if (r.cssText && r.cssText.indexOf('safe-area-inset') !== -1) { hasEnv = true; break; } } if (hasEnv) break; } } catch (e) {} return hasFit && hasEnv; })(),
        installNudge: typeof installNudge === 'function' && !!document.getElementById('installCard') && (() => { const eng = { workouts: [{}, {}, {}, {}, {}] }; return installNudge(eng, { canPrompt: true }).show === true && installNudge(eng, { canPrompt: true, standalone: true }).show === false && installNudge(eng, { canPrompt: false }).show === false && installNudge({ workouts: [{}] }, { canPrompt: true }).show === false; })(),
        onboardingPreview: !!document.getElementById('onboardingPreviewBtn') && !!document.getElementById('onboardingPreview') && typeof renderOnboardingPreview === 'function' && (() => { document.getElementById('onboardingObjective').value = 'seche'; document.getElementById('onbWeight').value = '80'; document.getElementById('onbHeight').value = '178'; renderOnboardingPreview(); const el = document.getElementById('onboardingPreview'); return !el.hidden && /kcal/.test(el.textContent) && /séances/.test(el.textContent); })(),
        macroBreakdown: typeof macroBreakdown === 'function' && (() => { const b = macroBreakdown({ dailyTarget: 2000, proteinG: 150, carbG: 200, fatG: 60 }); return b.length === 3 && b[0].key === 'protein' && b[0].pct === 30 && /muscle/i.test(b[0].role) && macroBreakdown(null).length === 0 && !!document.querySelector('#onboardingPreview .onb-macros'); })(),
        suggestedQuests: typeof suggestedQuests === 'function' && !!document.getElementById('questSuggestions') && (() => { const q = suggestedQuests({ agenda: [{ kind: 'sport', date: '2026-07-13', completed: false }], workouts: [], nutrition: [], focusSessions: [], profile: { weight: 80 }, quests: [] }, '2026-07-13'); return Array.isArray(q) && q.length >= 1 && q.length <= 4 && q.every(x => x.name && x.category && x.xp > 0) && q.some(x => x.key === 'session'); })(),
        objectiveNutrition: typeof objectiveNutrition === 'function' && (() => { const b = { weight: 80, height: 178, age: 30, sex: 'homme', activityLevel: 'modere' }; const s = objectiveNutrition('seche', b), m = objectiveNutrition('muscle', b), a = objectiveNutrition('athletique', b); return s && m && a && s.dailyTarget < a.dailyTarget && m.dailyTarget > a.dailyTarget && objectiveNutrition('zzz', b) === null; })(),
        objectiveEquipment: typeof filterByEquipment === 'function' && typeof exerciseAvailable === 'function' && (() => { const names = pr => pr.week.filter(s => s.kind === 'muscu').flatMap(s => s.exercises.map(e => e.name)); const bw = objectiveProgram('athletique', exercises, { perSession: 6, equipment: { kettlebell: false, pullup: false, vest: false, handles: false } }); const noKb = names(bw).every(n => { const ex = exercises.find(x => x.name === n); return ex && ex.kind !== 'Kettlebell' && ex.kind !== 'Barre de traction'; }); return noKb && names(bw).length >= 3; })(),
        birthdays: typeof birthdaysForDay === 'function' && typeof normalizeBirthday === 'function' && !!document.getElementById('birthdayForm') && !!document.getElementById('birthdayList'),
        ux2pass2: document.querySelectorAll('details.calendar-setting').length >= 3 && !document.querySelector('.trail-plan') && !!document.querySelector('.training-grid > article.panel .collapse-toggle'),
        ux3: typeof upcomingBirthdays === 'function' && !!document.getElementById('birthdayUpcoming') && !!document.querySelector('.training-grid > .trail-panel'),
        recurring: typeof recurrenceMatches === 'function' && typeof normalizeRecurring === 'function' && !!document.getElementById('recurringForm') && !!document.getElementById('recFreq') && !!document.getElementById('recurringList'),
        recSkip: typeof recurringOccurs === 'function' && typeof skipRecurringOn === 'function' && recurringOccurs({ id: 1, rule: { freq: 'weekly', interval: 1, weekdays: [1], startDate: '2026-07-06' }, skipLog: ['2026-07-13'] }, '2026-07-13') === false,
        habits: typeof habitsForDay === 'function' && typeof habitStreak === 'function' && !!document.getElementById('habitForm') && !!document.getElementById('habitList') && document.querySelectorAll('#habitDays input').length === 7,
        habitWeek: typeof habitWeekMap === 'function' && (m => m.length === 7 && m[6].key === '2026-07-10' && m[6].done === true)(habitWeekMap({ id: 1, weekdays: [], log: ['2026-07-10'] }, '2026-07-10')),
        habitsAtRisk: typeof habitsAtRisk === 'function' && !!document.getElementById('habitsAtRisk') && (() => { const r = habitsAtRisk([{ id: 1, name: 'Lecture', log: ['2026-07-05', '2026-07-06', '2026-07-07'] }, { id: 2, name: 'Eau', log: ['2026-07-07', '2026-07-08'] }], '2026-07-08'); return r.length === 1 && r[0].name === 'Lecture' && r[0].streak === 3 && habitsAtRisk(null, '2026-07-08').length === 0; })(),
        recDone: typeof completeRecurringOn === 'function' && (L => { const r = normalizeRecurring({ id: 1, doneLog: ['2026-07-07'] }); return r.doneLog.length === 1; })(),
        calSync: typeof normalizeCalendarUrl === 'function' && !!document.getElementById('calSubForm') && !!document.getElementById('calSubList') && !!document.getElementById('calSyncAll') && !!(window.desktop && typeof window.desktop.fetchCalendar === 'function' && typeof window.desktop.getCalendarSubs === 'function'),
        exIcons: typeof exerciseIcon === 'function' && exerciseIcon('Tractions').includes('viewBox="0 0 80 76"') && exerciseIcon('Tractions', true).includes('<animate') && exerciseIcon('Goblet squat kettlebell') !== exerciseIcon('Pompes classiques') && (document.querySelector('.exercise-card .ex-svg') ? document.querySelectorAll('.exercise-card .ex-svg').length >= 1 : true),
        icsRrule: typeof parseRRule === 'function' && (parseIcs('BEGIN:VEVENT\\r\\nUID:x\\r\\nSUMMARY:R\\r\\nDTSTART:20260706T090000\\r\\nRRULE:FREQ=WEEKLY;BYDAY=MO\\r\\nEND:VEVENT')[0]||{}).recurrence != null,
        icsExport: typeof buildRRuleLine === 'function' && buildIcs([{ id: 1, title: 'R', time: '09:00', rule: { freq: 'weekly', interval: 1, weekdays: [1], startDate: '2026-07-06' } }]).includes('RRULE:FREQ=WEEKLY'),
        todo: typeof todosForDay === 'function' && typeof normalizeTodo === 'function' && !!document.getElementById('todoForm') && !!document.getElementById('todoList') && !!document.getElementById('todoPriorityBtn'),
        comfort: !!document.getElementById('backToTop') && !!document.getElementById('densityToggle') && !!document.getElementById('appVersion'),
        dialogBackdrop: typeof bindDialogBackdropClose === 'function' && (() => { const d = document.getElementById('questDialog'); if (!d) return false; try { d.showModal(); d.dispatchEvent(new MouseEvent('click', { clientX: 0, clientY: 0, bubbles: true })); const closed = !d.open; if (d.open) d.close(); return closed; } catch (_) { return false; } })(),
        autoUpdate: !!(window.desktop && typeof window.desktop.installUpdate === 'function' && typeof window.desktop.onUpdateStatus === 'function') && !!document.getElementById('updateBanner') && !!document.getElementById('updateInstallBtn'),
        weekPlanner: typeof buildWeekPlan === 'function' && typeof generateAutomaticWeek === 'function' && document.querySelectorAll('#availabilityDays input').length === 7,
        volume: typeof volumeRamp === 'function' && !!document.getElementById('volStart') && typeof renderVolumeGoal === 'function',
        warmup: typeof warmupFor === 'function' && !!document.getElementById('guidedWarmupList'),
        cooldown: typeof cooldownFor === 'function' && !!document.getElementById('guidedCooldownList') && !!document.getElementById('guidedCooldown'),
        restSound: typeof guidedRestCue === 'function' && typeof restSoundEnabled === 'function' && !!document.getElementById('restSoundToggle'),
        restAdjust: typeof restBarPct === 'function' && typeof adjustRestSeconds === 'function' && typeof adjustGuidedRest === 'function' && !!document.getElementById('guidedRestMinus') && !!document.getElementById('guidedRestPlus') && !!document.getElementById('guidedRestBar') && restBarPct(30, 60) === 50 && adjustRestSeconds(75, -15) === 60 && adjustRestSeconds(595, 30) === 600,
        restTimerMobile: typeof formatClock === 'function' && typeof setGuidedRest === 'function' && !!document.getElementById('guidedRestPresets') && document.querySelectorAll('#guidedRestPresets [data-rest]').length === 5 && formatClock(90) === '1:30' && formatClock(45) === '0:45',
        exCount: (typeof exercises !== 'undefined') ? exercises.length : 0,
        achievements: typeof computeAchievements === 'function' && computeAchievements({ quests: [{ done: true }] }).total === 22 && computeAchievements({ streak: 30, fitnessObjective: 'seche' }).badges.find(b => b.id === 'objective-set').unlocked === true && document.querySelectorAll('#achievementList .achievement').length >= 10,
        lifetime: typeof lifetimeStats === 'function' && !!document.getElementById('lifetimeStats') && lifetimeStats({ workouts: [{ type: 'run', duration: 60, distance: 10 }] }).runKm === 10,
        levelUp: typeof leveledUp === 'function' && leveledUp(90, 110) === 2 && leveledUp(120, 150) === null,
        quests: document.querySelectorAll('#questList .quest').length,
        exercises: document.querySelectorAll('#exerciseCards .exercise-card').length,
        levelSet: (document.querySelector('#xpLabel')||{}).textContent || ''
      };
    })()`);
    console.log('CHECKS ' + JSON.stringify(checks));
    if (!checks.logicLoaded) errors.push('lib/logic.js non chargé (localDate/pct/computeStreak absents)');
    if (!checks.normalize) errors.push('normalizeState absente');
    if (!checks.photosApi) errors.push('API photos absente (loadGalleryPhotos/migratePhotosToDisk/desktop.savePhoto)');
    if (!checks.studyPlanner) errors.push('Planificateur de révision absent (studyPlanForm/planStudySessions/buildIcs)');
    if (!checks.myDay) errors.push('Vue Ma journée absente ou non rendue (myDayList/todayItems/myDaySummary)');
    if (!checks.charts) errors.push('Graphiques absents (chartGrid/weeklyAggregate/renderCharts)');
    if (!checks.weekView) errors.push('Vue Ma semaine absente (weekGrid/weekItems/renderWeekPage/openWeekPage)');
    if (!checks.printReport) errors.push('Bilan PDF absent (printReport/weeklySummary/renderPrintReport/printWeekReport)');
    if (!checks.theme) errors.push('Thème absent (themeToggle / variable --surface-2)');
    if (!checks.raceGoal) errors.push('Objectif de course absent (raceGoalType/raceGoalStatus/renderRaceGoal)');
    if (!checks.supplements) errors.push('Compléments absents (suppHeat/hydrationPlan/suppProteinTarget)');
    if (!checks.nutritionPlus) errors.push('Nutrition+ absente (supplementTiming/searchFoods/foodResults/suppTimingGrid)');
    if (!checks.kitchen) errors.push('Cuisine du jour absente (generateMeals/pantryList/mealSuggestions/envieStyles)');
    if (!checks.hydration) errors.push('Hydratation absente (waterStatus/waterPlus/waterMinus/hydraFill)');
    if (!checks.records) errors.push('Records perso absents (personalRecords/exerciseDetailNotes)');
    if (!checks.shopping) errors.push('Liste de courses absente (buildShoppingList/shoppingBlock/shoppingList/copyShoppingBtn)');
    if (!checks.agendaImport) errors.push('Import agenda absent (parseIcs/importIcs/importIcsKind/calendarAgendaPriority)');
    if (!checks.agendaUx) errors.push('UX agenda absente (weekQuickAdd/agendaFilters 5 filtres/importIcsWeek)');
    if (!checks.agendaSearch) errors.push('Recherche agenda absente (agendaMatch/agendaSearch)');
    if (!checks.agendaDay) errors.push('Vue Jour absente (renderDayView/renderAgenda/dayView/agendaViewSwitch 2 vues)');
    if (!checks.dayGrid) errors.push('Grille horaire absente (dayColumns/endTimeOf)');
    if (!checks.agendaDetails) errors.push('Détails événement absents (departureInfo/location/travel/notes)');
    if (!checks.agendaEdit) errors.push('Ajout rapide/édition détaillés absents (weekQuickLocation/Travel/Notes/Estimate/agendaEditForm/editAgendaNotes)');
    if (!checks.guidedFromPlan) errors.push('Séance guidée depuis le programme absente (startGuidedFromNames/openGuidedWorkout/guidedWorkoutDialog)');
    if (!checks.settingsPage) errors.push('Page Réglages absente (data-page=settings/.settings-page/3 conn-row/settingsTheme/settingsDensity)');
    if (!checks.dataIo) errors.push('Export/import données absents (exportDataBtn/importDataBtn/dataIoStatus)');
    if (!checks.s8Travel) errors.push('Trajet auto S.8 absent (isAllowedTravelUrl/travelModes/calendarAgendaEstimate/travelStartForm/travelHome/travelMode)');
    if (!checks.goalsZones) errors.push('Objectifs par zone absents (goalMatch/goalRank/TRAINING_GOALS/#exerciseGoal 8 options)');
    if (!checks.animEngine) errors.push('Moteur d’animation absent (buildAnimatedArt/EXERCISE_ANIM/frame-a/frame-b)');
    if (!checks.zonePlan) errors.push('Programme par zone absent (buildZonePlan/zoneTopExercises/zonePlanBtn/zonePlanDialog/zonePlanTable)');
    if (!checks.weekProgram) errors.push('Planificateur semaine absent (buildTrainingWeek/wpGoals 7/wpGenerate/wpSchedule)');
    if (!checks.birthdays) errors.push('Anniversaires absents (birthdaysForDay/normalizeBirthday/birthdayForm/birthdayList)');
    if (!checks.ux2pass2) errors.push('UX#2 passe 2 KO (3 details.calendar-setting / trail-plan retiré / collapse-toggle sur article.panel)');
    if (!checks.ux3) errors.push('D2/B3 KO (upcomingBirthdays / birthdayUpcoming / trail-panel regroupé dans training-grid)');
    if (!checks.recurring) errors.push('Récurrence KO (recurrenceMatches/normalizeRecurring/recurringForm/recFreq/recurringList)');
    if (!checks.habits) errors.push('Habitudes KO (habitsForDay/habitStreak/habitForm/habitList/habitDays 7 jours)');
    if (!checks.recDone) errors.push('Validation récurrent KO (completeRecurringOn/doneLog)');
    if (!checks.calSync) errors.push('Sync calendrier KO (normalizeCalendarUrl/calSubForm/calSubList/calSyncAll/desktop.fetchCalendar)');
    if (!checks.exIcons) errors.push('Illustrations exercices KO (exerciseIcon viewBox/animate/patterns distincts)');
    if (!checks.icsRrule) errors.push('Import RRULE KO (parseRRule / parseIcs ne remonte pas recurrence)');
    if (!checks.icsExport) errors.push('Export RRULE KO (buildRRuleLine / buildIcs ne produit pas de RRULE)');
    if (!checks.todo) errors.push('To-Do absente (todosForDay/normalizeTodo/todoForm/todoList/todoPriorityBtn)');
    if (!checks.comfort) errors.push('Confort absent (backToTop/densityToggle/appVersion)');
    if (!checks.autoUpdate) errors.push('Auto-update absent (desktop.installUpdate/onUpdateStatus/updateBanner)');
    if (!checks.weekPlanner) errors.push('Planificateur hebdo absent (buildWeekPlan/generateAutomaticWeek/7 cases jours)');
    if (!checks.volume) errors.push('Montée en volume absente (volumeRamp/volStart/renderVolumeGoal)');
    if (!checks.warmup) errors.push('Échauffement guidé absent (warmupFor/guidedWarmupList)');
    if (!checks.cooldown) errors.push('Retour au calme absent (cooldownFor/guidedCooldownList)');
    if (checks.exCount < 37) errors.push('Bibliothèque incomplète : ' + checks.exCount + ' exercices (attendu ≥ 37)');
    if (checks.quests < 1) errors.push('#questList vide → render() ne s\'est pas exécuté');
    if (checks.exercises < 1) errors.push('#exerciseCards vide → renderExerciseLibrary KO');
  } catch (e) {
    errors.push('exception: ' + e.message);
  }

  clearTimeout(bail);
  if (errors.length) { console.error('SMOKE FAIL:\n' + errors.join('\n')); app.exit(1); }
  else { console.log('SMOKE OK'); app.exit(0); }
});
